// Archetype packs: declarative content bundles. A pack carries the
// routing library, phase dictionary, selection rules, scheduling
// constraints, and screen copy for one planning archetype family.
// The app composes a project from archetype + industry + ERP dialect;
// nothing in app.js should hardcode pack content.

const ArchetypePacks = {
  "pharma-batch": {
    id: "pharma-batch",
    name: "Pharma Batch / Campaign",
    copy: {
      eyebrow: "SAP PP-PI Master Recipe Library",
      title: "Operations now decompose into setup, run, labor, teardown, disassembly, and cleanup phases.",
      text: "The demo assumes SAP PP-PI semantics: process orders consume master recipes, operations run on resources, and every operation carries phase-level time drivers for APS simulation.",
      pickerLabel: "Master Recipe",
    },
    phases: [
      { key: "setup", label: "Setup", description: "Prepares the resource before the process order run; fixed time independent of quantity." },
      { key: "machine", label: "Machine Run", description: "Variable processing time driven by run rate and process order quantity." },
      { key: "labor", label: "Labor", description: "Operator effort required to execute, monitor, sample, or verify the phase." },
      { key: "teardown", label: "Teardown", description: "Post-run reset time before the resource can be released or cleaned." },
      { key: "disassembly", label: "Disassembly", description: "Breakdown time for tools, change parts, filters, or product-contact assemblies." },
      { key: "cleanup", label: "Cleanup", description: "Sanitization or eco-cleaning time required before the next material batch." },
    ],
    routings: [
      {
        id: "RT-TAB-DC-001",
        family: "Oral Solid Dose",
        type: "Direct Compression Tablet",
        batchSize: "250 kg",
        status: "Approved",
        gmp: "High",
        campaign: "Yes",
        cleaning: "Product-contact clean",
        qaRelease: "Yes",
        operations: [
          ["10", "Raw Material Staging", "WH-STAGE", "1.0 h", "-", "0.5 h", "100%", "Pick API and excipients"],
          ["20", "Weighing & Dispensing", "DISP-ROOM", "0.5 h", "100 kg/h", "0.5 h", "99.8%", "GMP double check"],
          ["30", "Pre-blending", "BLENDER-STD", "0.5 h", "500 kg/h", "0.5 h", "99.5%", "Dry blend"],
          ["40", "Lubrication Blend", "BLENDER-STD", "0.25 h", "600 kg/h", "0.25 h", "99.8%", "Magnesium stearate addition"],
          ["50", "In-process Blend Sampling", "IPC-LAB", "0.25 h", "-", "4.0 h", "100%", "Blend uniformity"],
          ["60", "Tablet Compression", "TAB-PRESS", "1.0 h", "120,000 tab/h", "0.5 h", "98.5%", "Compression with IPC checks"],
          ["70", "Dedusting & Metal Detection", "METAL-DET", "0.25 h", "150,000 tab/h", "0.25 h", "99.9%", "Critical control"],
          ["80", "Bulk Tablet Hold", "BULK-HOLD", "0.0 h", "-", "12.0 h", "100%", "Await QA / packaging"],
          ["90", "QA Bulk Release", "QA-BULK", "0.5 h", "-", "24.0 h", "100%", "Required before packaging"],
        ],
      },
      {
        id: "RT-TAB-WG-001",
        family: "Oral Solid Dose",
        type: "Wet Granulated Tablet",
        batchSize: "250 kg",
        status: "Approved",
        gmp: "High",
        campaign: "Yes",
        cleaning: "Major clean if product family changes; standard clean within campaign",
        qaRelease: "Yes",
        operations: [
          ["10", "Raw Material Staging", "WH-STAGE", "1.0 h", "-", "0.5 h", "100%", "Materials staged"],
          ["20", "Weighing & Dispensing", "DISP-ROOM", "0.5 h", "100 kg/h", "0.5 h", "99.8%", "GMP double check"],
          ["30", "Dry Mixing", "GRANULATOR", "0.5 h", "300 kg/h", "0.25 h", "99.5%", "Pre-granulation mix"],
          ["40", "Binder Preparation", "LIQ-PREP", "0.5 h", "200 L/h", "0.25 h", "99.5%", "Binder solution"],
          ["50", "Wet Granulation", "GRANULATOR", "0.75 h", "250 kg/h", "0.5 h", "98.5%", "Critical process step"],
          ["60", "Wet Milling", "MILL-WET", "0.5 h", "250 kg/h", "0.25 h", "99.0%", "Size reduction"],
          ["70", "Fluid Bed Drying", "FBD", "1.0 h", "150 kg/h", "0.5 h", "97.5%", "Dry to LOD target"],
          ["80", "Dry Milling", "MILL-DRY", "0.5 h", "300 kg/h", "0.25 h", "99.0%", "Final particle size"],
          ["90", "Final Blending", "BLENDER-STD", "0.5 h", "500 kg/h", "0.5 h", "99.5%", "Extragranular excipients"],
          ["100", "Lubrication Blend", "BLENDER-STD", "0.25 h", "600 kg/h", "0.25 h", "99.8%", "Lubricant addition"],
          ["110", "Blend Uniformity Testing", "IPC-LAB", "0.25 h", "-", "6.0 h", "100%", "QA hold"],
          ["120", "Tablet Compression", "TAB-PRESS", "1.0 h", "100,000 tab/h", "0.5 h", "98.0%", "Compression"],
          ["130", "Coating", "COATER", "1.0 h", "80,000 tab/h", "1.0 h", "97.5%", "Optional step"],
          ["140", "Bulk QA Release", "QA-BULK", "0.5 h", "-", "24.0 h", "100%", "Required before packaging"],
        ],
      },
      {
        id: "RT-CAP-STD-001",
        family: "Oral Solid Dose",
        type: "Hard Capsule",
        batchSize: "250 kg",
        status: "Approved",
        gmp: "High",
        campaign: "Yes",
        cleaning: "Product-contact clean",
        qaRelease: "Yes",
        operations: [
          ["10", "Raw Material Staging", "WH-STAGE", "1.0 h", "-", "0.5 h", "100%", "API, excipients, capsule shells"],
          ["20", "Weighing & Dispensing", "DISP-ROOM", "0.5 h", "100 kg/h", "0.5 h", "99.8%", "GMP check"],
          ["30", "Blending", "BLENDER-STD", "0.5 h", "400 kg/h", "0.5 h", "99.5%", "Capsule fill blend"],
          ["40", "Blend Sampling", "IPC-LAB", "0.25 h", "-", "4.0 h", "100%", "Blend uniformity"],
          ["50", "Capsule Filling", "CAP-FILLER", "1.0 h", "90,000 cap/h", "0.5 h", "97.5%", "Fill weight IPC"],
          ["60", "Capsule Polishing", "CAP-POLISH", "0.25 h", "100,000 cap/h", "0.25 h", "99.5%", "Dust removal"],
          ["70", "Metal Detection", "METAL-DET", "0.25 h", "120,000 cap/h", "0.25 h", "99.9%", "Critical control"],
          ["80", "Bulk QA Release", "QA-BULK", "0.5 h", "-", "24.0 h", "100%", "Required before packaging"],
        ],
      },
      {
        id: "RT-LIQ-SYR-001",
        family: "Liquids",
        type: "Oral Syrup",
        batchSize: "1,000 L",
        status: "Approved",
        gmp: "High",
        campaign: "Conditional",
        cleaning: "Liquid product-contact clean; microbial clean if hold time exceeded",
        qaRelease: "Yes",
        operations: [
          ["10", "Raw Material Staging", "WH-STAGE", "1.0 h", "-", "0.5 h", "100%", "API, excipients, bottles"],
          ["20", "Weighing & Dispensing", "DISP-ROOM", "0.5 h", "100 kg/h", "0.5 h", "99.8%", "GMP check"],
          ["30", "Water Charging", "LIQ-TANK", "0.25 h", "1,000 L/h", "0.25 h", "100%", "Purified water"],
          ["40", "Syrup Base Preparation", "LIQ-TANK", "0.5 h", "800 L/h", "0.25 h", "99.5%", "Sweetener/preservatives"],
          ["50", "API Addition & Mixing", "LIQ-TANK", "0.5 h", "600 L/h", "0.5 h", "99.0%", "Critical mixing"],
          ["70", "Filtration", "FILTER-LIQ", "0.5 h", "500 L/h", "0.5 h", "99.0%", "Bioburden/particulate control"],
          ["90", "QC Testing", "QC-LAB", "0.5 h", "-", "24.0 h", "100%", "Assay, pH, microbial"],
          ["100", "Bottle Filling", "LIQ-FILLER", "1.0 h", "3,000 bot/h", "0.5 h", "98.0%", "Fill volume IPC"],
          ["120", "Labeling & Cartoning", "PACK-LIQ", "0.5 h", "2,500 bot/h", "0.5 h", "99.0%", "Final pack"],
        ],
      },
      {
        id: "RT-STER-VIAL-001",
        family: "Sterile",
        type: "Aseptic Liquid Vial",
        batchSize: "Sterile batch",
        status: "Approved",
        gmp: "High",
        campaign: "Restricted",
        cleaning: "Sterile clean / SIP / CIP as applicable",
        qaRelease: "Yes",
        operations: [
          ["10", "Raw Material Staging", "WH-STAGE", "1.0 h", "-", "0.5 h", "100%", "API, excipients, vials, stoppers"],
          ["20", "Sterile Component Prep", "COMP-PREP", "1.0 h", "5,000 unit/h", "1.0 h", "99.0%", "Wash / sterilize components"],
          ["40", "Solution Preparation", "STERILE-TANK", "1.0 h", "300 L/h", "0.5 h", "99.0%", "Controlled environment"],
          ["50", "Bioburden Sampling", "QC-MICRO", "0.25 h", "-", "8.0 h", "100%", "Microbiological hold"],
          ["60", "Sterile Filtration", "STERILE-FILTER", "1.0 h", "200 L/h", "0.5 h", "98.5%", "0.22 micron filtration"],
          ["70", "Aseptic Filling", "ASEPTIC-FILL", "2.0 h", "6,000 vial/h", "0.5 h", "97.0%", "Grade A/B environment"],
          ["90", "Visual Inspection", "VIS-INSP", "1.0 h", "3,000 vial/h", "1.0 h", "98.0%", "Manual/automated inspection"],
          ["100", "Sterility Testing", "QC-MICRO", "0.5 h", "-", "336.0 h", "100%", "14-day sterility hold"],
          ["110", "Final QA Release", "QA-FINAL", "0.5 h", "-", "48.0 h", "100%", "Batch release"],
        ],
      },
      {
        id: "RT-PACK-BLISTER-001",
        family: "Packaging",
        type: "Blister Pack",
        batchSize: "Packaging order",
        status: "Approved",
        gmp: "High",
        campaign: "By format",
        cleaning: "Line clearance required",
        qaRelease: "Yes",
        operations: [
          ["10", "Packaging Material Staging", "WH-PACK", "1.0 h", "-", "0.5 h", "100%", "Foil, PVC, cartons, leaflets"],
          ["20", "Line Clearance", "PACK-QA", "0.5 h", "-", "0.5 h", "100%", "GMP required"],
          ["30", "Blister Forming & Filling", "BLISTER-LINE", "1.5 h", "300 blister/min", "0.5 h", "98.0%", "Includes print checks"],
          ["40", "Leak Testing", "IPC-PACK", "0.25 h", "-", "1.0 h", "100%", "Periodic IPC"],
          ["50", "Cartoning", "CARTONER", "0.75 h", "180 carton/min", "0.5 h", "99.0%", "Carton + leaflet"],
          ["60", "Serialization", "SERIALIZER", "0.5 h", "150 carton/min", "0.5 h", "99.5%", "Market-dependent"],
          ["80", "Final Packaging QA", "QA-PACK", "0.5 h", "-", "24.0 h", "100%", "Final release"],
        ],
      },
    ],
    cleaningRoutings: [
      { id: "RT-CLEAN-STD-001", name: "Standard Product-Contact Cleaning", duration: "4-8 h", steps: "Disassembly, pre-rinse, detergent wash, final rinse, drying, QA verification" },
      { id: "RT-CLEAN-MAJOR-001", name: "Major Product Changeover Cleaning", duration: "12-36 h", steps: "Full strip-down, residue removal, detergent wash, rinse, drying, swab sampling, lab analysis, QA release" },
      { id: "RT-CLEAN-POTENT-001", name: "Potent API / High-Containment Cleaning", duration: "24-72 h", steps: "Containment shutdown, PPE/decon, strip-down, neutralization, wash, rinse, controlled drying, QC residue analysis, QA release" },
    ],
    routingRules: [
      ["Tablet, direct compression", "Use RT-TAB-DC-001"],
      ["Tablet, wet granulation", "Use RT-TAB-WG-001"],
      ["Capsule", "Use RT-CAP-STD-001"],
      ["Oral liquid", "Use RT-LIQ-SYR-001"],
      ["Sterile vial", "Use RT-STER-VIAL-001"],
      ["Blister presentation", "Add RT-PACK-BLISTER-001 after bulk release"],
      ["Potent API", "Use high-containment work centers and RT-CLEAN-POTENT-001"],
      ["Different API", "Major clean"],
      ["Sterile product", "Sterile cleaning / SIP / environmental release required"],
      ["Allergen / beta-lactam / hormone / cytotoxic", "Dedicated or segregated routing required"],
    ],
    schedulingConstraints: [
      ["QA Hold", "Bulk cannot move to packaging before QA bulk release"],
      ["Sterility Hold", "Sterile injectable cannot be released before sterility testing is complete"],
      ["Cleaning Dependency", "Equipment cannot start next batch before cleaning is complete and released"],
      ["Campaigning", "Similar products may run back-to-back if validated"],
      ["Potent API", "Potent products require containment and stricter cleaning"],
      ["Shelf-life", "Packaging should occur within validated bulk hold time"],
      ["Line Clearance", "Packaging cannot start before QA line clearance"],
      ["Serialization", "Required for markets where serialization is mandatory"],
      ["Sampling", "IPC and QC operations may create hard gates or soft planning constraints"],
    ],
  },

  "discrete-assembly": {
    id: "discrete-assembly",
    name: "Discrete Assembly / Job Shop",
    copy: {
      eyebrow: "Discrete Routing Library",
      title: "Operations decompose into setup, run, labor, teardown, tooling, and changeover drivers.",
      text: "The demo assumes discrete semantics: production orders consume routings, operations run on workstations, and BOM availability plus sequence-dependent setup drive feasibility.",
      pickerLabel: "Routing",
    },
    phases: [
      { key: "setup", label: "Setup", description: "Fixture, program, and first-article preparation before the run; independent of quantity." },
      { key: "machine", label: "Machine Run", description: "Variable processing time driven by cycle rate and order quantity." },
      { key: "labor", label: "Labor", description: "Operator effort to load, assemble, inspect, or tend the operation." },
      { key: "teardown", label: "Teardown", description: "Post-run reset before the workstation is released to the next job." },
      { key: "disassembly", label: "Tooling Breakdown", description: "Removal of fixtures, jigs, and change parts after the run." },
      { key: "cleanup", label: "Changeover", description: "Sequence-dependent changeover work before the next product variant." },
    ],
    routings: [
      {
        id: "RT-ASM-GBX-001",
        family: "Drivetrain",
        type: "Gearbox Assembly",
        batchSize: "Lot of 50",
        status: "Released",
        gmp: "n/a",
        campaign: "By variant",
        cleaning: "Changeover wipe-down between variants",
        qaRelease: "Final test required",
        operations: [
          ["10", "Component Kitting", "WH-KIT", "0.5 h", "-", "0.5 h", "100%", "BOM completeness check"],
          ["20", "Sub-assembly: Gear Train", "ASM-CELL-1", "0.5 h", "12 unit/h", "0.25 h", "99.0%", "Skilled fitters required"],
          ["30", "Housing Preparation", "ASM-CELL-2", "0.25 h", "20 unit/h", "0.25 h", "99.5%", "Bearing press"],
          ["40", "Main Assembly", "ASM-LINE-A", "0.75 h", "8 unit/h", "0.5 h", "98.5%", "Torque-controlled stations"],
          ["50", "Oil Fill & Leak Test", "TEST-RIG-1", "0.5 h", "10 unit/h", "0.5 h", "98.0%", "Shared test stand"],
          ["60", "Run-in & Noise Test", "TEST-RIG-2", "0.5 h", "6 unit/h", "1.0 h", "97.5%", "Bottleneck resource"],
          ["70", "Final QC Audit", "QC-BENCH", "0.25 h", "-", "2.0 h", "100%", "Sampling plan per lot"],
          ["80", "Pack & Label", "PACK-DISC", "0.25 h", "15 unit/h", "0.25 h", "99.5%", "Variant-specific labels"],
        ],
      },
      {
        id: "RT-MACH-HSG-001",
        family: "Machining",
        type: "Housing Machining",
        batchSize: "Lot of 120",
        status: "Released",
        gmp: "n/a",
        campaign: "By material",
        cleaning: "Chip clearance and coolant check at changeover",
        qaRelease: "CMM report required",
        operations: [
          ["10", "Raw Casting Staging", "WH-RAW", "0.5 h", "-", "0.5 h", "100%", "Casting batch traceability"],
          ["20", "CNC Milling Op 1", "CNC-MILL-3", "1.0 h", "10 unit/h", "0.5 h", "98.0%", "Fixture A; alternate CNC-MILL-4"],
          ["30", "CNC Milling Op 2", "CNC-MILL-3", "0.75 h", "12 unit/h", "0.5 h", "98.5%", "Reentrant on same machine"],
          ["40", "Drilling & Tapping", "DRILL-CTR", "0.5 h", "25 unit/h", "0.25 h", "99.0%", "Tool life monitoring"],
          ["50", "Deburr & Wash", "DEBURR-ST", "0.25 h", "30 unit/h", "0.25 h", "99.5%", "Manual finish"],
          ["60", "CMM Inspection", "CMM-LAB", "0.5 h", "-", "4.0 h", "100%", "First article plus sampling"],
        ],
      },
    ],
    cleaningRoutings: [
      { id: "RT-CHG-VAR-001", name: "Variant Changeover", duration: "0.5-2 h", steps: "Fixture swap, program load, first-article inspection, line restock" },
      { id: "RT-CHG-MAT-001", name: "Material Changeover", duration: "1-4 h", steps: "Chip clearance, coolant check, tool change, calibration, first article" },
    ],
    routingRules: [
      ["Standard gearbox variant", "Use RT-ASM-GBX-001"],
      ["Machined housing", "Use RT-MACH-HSG-001 before assembly"],
      ["New variant", "First-article inspection gate before lot release"],
      ["Shared test rig", "Sequence lots to minimize rig idle time"],
      ["Material change on CNC", "Apply RT-CHG-MAT-001 changeover"],
    ],
    schedulingConstraints: [
      ["BOM Availability", "Assembly cannot start before all kitted components are available"],
      ["Sequence-dependent Setup", "Variant order on a line changes setup duration"],
      ["Alternate Machines", "Operations may move to qualified alternates at a rate penalty"],
      ["Skills", "Sub-assembly requires certified fitters; capacity follows the shift roster"],
      ["Test Stand Bottleneck", "Shared rigs gate throughput across product families"],
      ["Rework Loops", "Failed tests re-enter the routing upstream and consume capacity"],
    ],
  },
};

// Which planning archetype uses which content pack. Unmapped archetypes
// fall back to the pharma pack until they get content of their own.
const archetypePackMap = {
  "discrete-assembly": "discrete-assembly",
  "job-shop": "discrete-assembly",
  "flow-shop": "discrete-assembly",
  "cto-eto": "discrete-assembly",
};
