// ImplementationOS -- scripted tutorial mode.
//
// Audio files are optional. Generate voiceover WAVs with the matching file
// names and place them under ./audio/tutorial/. Captions and spotlight focus
// work even when the audio files are not present.

const tutorialScript = [
  {
    id: "welcome",
    stepId: "welcome",
    focus: ".stage-body",
    audio: "audio/tutorial/01-welcome.wav",
    title: "Start with the journey",
    text: "Welcome to ImplementationOS for the Digital Manufacturing stack. This guided flow turns implementation decisions into a living configuration model, one clear screen at a time.",
  },
  {
    id: "implementation-intent",
    stepId: "scope",
    focus: ".scope-selection-strip",
    audio: "audio/tutorial/02-implementation-intent.wav",
    title: "Define the implementation intent",
    text: "Start by choosing the capability layers in scope. The selected stack at the top summarizes the answer, while each card says whether it is selected, available, or unavailable.",
  },
  {
    id: "system-landscape",
    stepId: "architecture",
    focus: ".arch-wrap",
    audio: "audio/tutorial/03-system-landscape.wav",
    title: "Map the system landscape",
    text: "Now translate intent into systems. Confirm the ERP source, planning layer, execution layer, shop-floor signals, and any satellite systems that shape the implementation.",
  },
  {
    id: "industry-context",
    stepId: "industry",
    focus: ".industry-picker",
    audio: "audio/tutorial/04-industry-context.wav",
    title: "Choose industry context",
    text: "Select every industry specialization the project must cover. The model supports portfolios, so one implementation can include multiple product families, sites, or business units.",
  },
  {
    id: "archetype",
    stepId: "archetype",
    focus: ".pick-grid",
    audio: "audio/tutorial/05-archetype.wav",
    title: "Select compatible operating patterns",
    text: "Choose the operating archetypes that truly shape the project. Incompatible cards stay visible for context, but only compatible patterns can enter the model.",
  },
  {
    id: "dialect",
    stepId: "dialect",
    focus: ".derive",
    audio: "audio/tutorial/06-dialect.wav",
    title: "Confirm the planning dialect",
    text: "The app synthesizes industry and archetype into a planning dialect. Use this screen to confirm the ERP vocabulary the customer actually uses.",
  },
  {
    id: "migration",
    stepId: "migration",
    focus: ".choice-grid",
    audio: "audio/tutorial/07-migration.wav",
    title: "Flag migration risk early",
    text: "If an S/4 or similar migration is on the roadmap, the implementation should avoid brittle one-off mappings and carry that risk into readiness.",
  },
  {
    id: "master-purpose",
    stepId: "master-purpose",
    focus: ".master-toggle",
    audio: "audio/tutorial/08-master-purpose.wav",
    title: "Decide whether Master Planning is in scope",
    text: "Master Planning is optional. Use it when the project needs a period-level supply plan before detailed planning, scheduling, dispatch, or execution takes over.",
  },
  {
    id: "master-policy",
    stepId: "master-policy",
    focus: ".master-profile",
    audio: "audio/tutorial/09-master-policy.wav",
    title: "Define the master planning policies",
    text: "This layer should not sequence every operation. It sets rough-cut capacity, planning policies, and bucket-level feasibility before the next layer takes over.",
  },
  {
    id: "master-handoff",
    stepId: "master-handoff",
    focus: ".master-profile",
    audio: "audio/tutorial/10-master-handoff.wav",
    title: "Define the downstream handoff",
    text: "Confirm what Master Planning hands downstream: firmed orders, pegging, overloads, inventory projection, or another release package.",
  },
  {
    id: "capacity-basics",
    stepId: "calendar-gantt-intro",
    focus: ".gantt-wrap",
    audio: "audio/tutorial/11-capacity-basics.wav",
    title: "Understand capacity before configuring it",
    text: "This teaching screen shows that capacity is only the time a resource is actually open. Nights, breaks, holidays, and maintenance cannot be scheduled.",
  },
  {
    id: "calendars-capacity",
    stepId: "calendar",
    focus: ".capacity-profile",
    audio: "audio/tutorial/12-calendars-capacity.wav",
    title: "Configure calendars and capacity",
    text: "Capture the availability layers, shift pattern, exceptions, and capacity modifiers. This is how the planning engine knows whether open time is really usable.",
  },
  {
    id: "capacity-preview",
    stepId: "calendar-gantt-preview",
    focus: ".gantt-wrap",
    audio: "audio/tutorial/13-capacity-preview.wav",
    title: "Preview the calendar model",
    text: "Review the resulting capacity timeline. This is a simplified day view of how the chosen calendar model changes each resource's usable time.",
  },
  {
    id: "bottleneck-basics",
    stepId: "bottleneck-intro",
    focus: ".gantt-wrap",
    audio: "audio/tutorial/14-bottleneck-basics.wav",
    title: "Introduce the bottleneck concept",
    text: "A bottleneck is the resource everything waits on. The app explains the concept without assuming the customer already knows where the constraint is.",
  },
  {
    id: "bottleneck",
    stepId: "constraint",
    focus: ".choice-grid",
    audio: "audio/tutorial/15-bottleneck.wav",
    title: "Capture the bottleneck hypothesis",
    text: "Ask whether the customer sees a stable bottleneck, a shifting bottleneck, or no clear constraint yet. This records a hypothesis, not a forced answer.",
  },
  {
    id: "bottleneck-preview",
    stepId: "bottleneck-preview",
    focus: ".gantt-wrap",
    audio: "audio/tutorial/16-bottleneck-preview.wav",
    title: "Preview the constraint pattern",
    text: "This preview draws the bottleneck hypothesis against the schedule. It makes clear that the planning engine can recompute the binding resource each run.",
  },
  {
    id: "department-taxonomy",
    stepId: "areas",
    focus: ".taxonomy-grid",
    audio: "audio/tutorial/17-department-taxonomy.wav",
    title: "Choose representative department types",
    text: "Select department taxonomies rather than asking for real plant names. The generated dataset will be representative and replaceable by customer data later.",
  },
  {
    id: "resource-taxonomy",
    stepId: "workcenters",
    focus: ".taxonomy-grid",
    audio: "audio/tutorial/18-resource-taxonomy.wav",
    title: "Choose resource types",
    text: "Pick the resource types that shape capacity: lines, work centers, tanks, people, labs, tools, or other constraints. These seed the representative model.",
  },
  {
    id: "tank-basics",
    stepId: "tank-intro",
    focus: ".tank-wrap",
    audio: "audio/tutorial/19-tank-basics.wav",
    title: "Explain dynamic volume assets",
    text: "Tanks and silos are not ordinary machines or shelves. Their feasibility depends on live occupancy, flow, cleaning state, and product eligibility.",
  },
  {
    id: "volume-storage",
    stepId: "volume-storage",
    focus: ".volume-storage-profile",
    audio: "audio/tutorial/20-volume-storage.wav",
    title: "Decide whether volume storage is in scope",
    text: "Use this screen when tanks, vats, silos, buffers, or drums affect feasibility. If they do not matter, mark them out of scope and move on.",
  },
  {
    id: "tank-preview",
    stepId: "tank-preview",
    focus: ".tank-wrap",
    audio: "audio/tutorial/21-tank-preview.wav",
    title: "Preview tank behavior over time",
    text: "The preview shows fill, hold, drain, heel, and capacity limits over a cycle. It makes tank scheduling visible instead of hiding it in a duration.",
  },
  {
    id: "classification",
    stepId: "attr-classification",
    focus: ".attr-chips",
    audio: "audio/tutorial/22-classification.wav",
    title: "Capture classification attributes",
    text: "Attributes begin with classification and grouping. These fields later drive changeovers, campaigns, reporting, and eligibility rules.",
  },
  {
    id: "descriptive",
    stepId: "attr-descriptor",
    focus: ".attr-chips",
    audio: "audio/tutorial/23-descriptive.wav",
    title: "Capture descriptive attributes",
    text: "Descriptive fields explain what the item is. The tutorial keeps them representative until real master data replaces the generated examples.",
  },
  {
    id: "planning-fields",
    stepId: "attr-planning",
    focus: ".attr-chips",
    audio: "audio/tutorial/24-planning-fields.wav",
    title: "Capture planning fields",
    text: "Planning fields tell the model how an item behaves: lead times, lot sizes, shelf life, storage rules, and other planning-relevant properties.",
  },
  {
    id: "variants",
    stepId: "attr-variant",
    focus: ".attr-chips",
    audio: "audio/tutorial/25-variants.wav",
    title: "Capture product variants",
    text: "Variants describe sellable or manufacturable differences. They may affect routing, packaging, eligibility, sequencing, or material availability.",
  },
  {
    id: "batch-serial",
    stepId: "attr-batchSerial",
    focus: ".attr-chips",
    audio: "audio/tutorial/26-batch-serial.wav",
    title: "Capture batch and serial behavior",
    text: "Batch and serial attributes matter for traceability, potency, expiry, genealogy, and regulated execution feedback.",
  },
  {
    id: "quality-params",
    stepId: "attr-quality",
    focus: ".attr-chips",
    audio: "audio/tutorial/27-quality-params.wav",
    title: "Capture quality parameters",
    text: "Quality parameters describe what must be true about the item or process. In regulated environments, they connect planning to batch records and release evidence.",
  },
  {
    id: "transition-basics",
    stepId: "transition-intro",
    focus: ".transition-sequence",
    audio: "audio/tutorial/28-transition-basics.wav",
    title: "Explain setup, changeover, and cleaning loss",
    text: "Between production runs, the line loses capacity to setup, changeover, cleaning, teardown, or other transitions. The model must account for that lost time.",
  },
  {
    id: "setup-cleaning",
    stepId: "transitions",
    focus: ".transition-profile",
    audio: "audio/tutorial/29-setup-cleaning.wav",
    title: "Configure transition rules",
    text: "Define what inserts transitions, whether they block the resource, and whether they are driven by SKU, family, attribute, recipe, or cleaning state.",
  },
  {
    id: "transition-preview",
    stepId: "transition-preview",
    focus: ".transition-sequence",
    audio: "audio/tutorial/30-transition-preview.wav",
    title: "Preview transition cost",
    text: "This preview shows the gaps between runs. Wider gaps cost more capacity, and concurrent transitions can overlap rather than stop the resource.",
  },
  {
    id: "bom-profile",
    stepId: "bom",
    focus: ".bom-profile",
    audio: "audio/tutorial/31-bom-profile.wav",
    title: "Describe the BOM profile",
    text: "BOMs can be multilevel, single-level, recipe-like, phantom-heavy, recursive, allocation-based, or order-level. Capture how product structure reaches planning.",
  },
  {
    id: "critical-supplies",
    stepId: "supplies",
    focus: ".supply-profile",
    audio: "audio/tutorial/32-critical-supplies.wav",
    title: "Mark critical supplies",
    text: "Not every material should hard-stop a schedule. Use lead time, storage capacity, shelf life, transfer risk, and substitutability to decide what is truly binding.",
  },
  {
    id: "workforce-basics",
    stepId: "workforce-intro",
    focus: ".gantt-wrap",
    audio: "audio/tutorial/33-workforce-basics.wav",
    title: "Explain workforce constraints",
    text: "Machines do not run themselves. Skilled people, qualifications, absences, and shift coverage can gate a schedule just like equipment.",
  },
  {
    id: "workforce-planning",
    stepId: "workforce",
    focus: ".workforce-profile",
    audio: "audio/tutorial/34-workforce-planning.wav",
    title: "Set workforce planning depth",
    text: "Choose how deeply to model workforce constraints. Some environments only need shift coverage; others need named skills, qualifications, and deployment rules.",
  },
  {
    id: "workforce-preview",
    stepId: "workforce-preview",
    focus: ".gantt-wrap",
    audio: "audio/tutorial/35-workforce-preview.wav",
    title: "Preview workforce impact",
    text: "The preview shows how skilled secondary resources constrain primary machines. A job waits if the right qualified person is not available.",
  },
  {
    id: "dispatch-intent",
    stepId: "dispatch-purpose",
    focus: ".master-toggle",
    audio: "audio/tutorial/36-dispatch-intent.wav",
    title: "Decide how work reaches the floor",
    text: "Dispatching decides how planned work becomes shop-floor action. Choose whether there is a separate dispatch layer or direct release through planning or MES.",
  },
  {
    id: "dispatch-rules",
    stepId: "dispatch-control",
    focus: ".master-profile",
    audio: "audio/tutorial/37-dispatch-rules.wav",
    title: "Define dispatch rules",
    text: "Dispatch rules control sequence adherence, due-date protection, WIP, changeover preservation, and how quickly the floor reacts to disruption.",
  },
  {
    id: "execution-feedback",
    stepId: "execution",
    focus: ".execution-profile",
    audio: "audio/tutorial/38-execution-feedback.wav",
    title: "Close the loop with execution feedback",
    text: "Execution feedback can come from MES, ERP, or both. Capture starts, completions, partials, scrap, yields, timestamps, phases, steps, and confirmations.",
  },
  {
    id: "try-variant",
    stepId: "variant",
    focus: ".variant-card",
    audio: "audio/tutorial/39-try-variant.wav",
    title: "Try a governed variant",
    text: "Variants let the team test a modeling decision before committing it. The branch history becomes part of the evidence trail rather than an undocumented side path.",
  },
  {
    id: "readiness",
    stepId: "readiness",
    focus: ".readiness-hero",
    audio: "audio/tutorial/40-readiness.wav",
    title: "Review readiness",
    text: "Readiness is computed from the decisions made so far: scope, model completeness, data issues, risk, and evidence. It shows what still needs attention.",
  },
  {
    id: "handoff",
    stepId: "handoff",
    focus: ".summary-grid",
    audio: "audio/tutorial/41-handoff.wav",
    title: "Hand off the implementation model",
    text: "The final screen exports the configuration, decisions, representative dataset, evidence, and notes. The handoff is generated from the journey, not recreated afterward.",
  },
];

window.tutorialScript = tutorialScript;

