import {validateScenario,inputDifferences} from './scenario-records.js?v=17';
import {cases,caseFor,projectScenario,configurationKey,snapshot} from './scenarios.js?v=17';
import {mountJourney} from './journey.js?v=17';
import {createModel,topics,rules,time} from './model.js?v=17';
import {tankProfile,skillProfile} from './engine.js?v=17';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let model;try{model=JSON.parse(localStorage.getItem('northworks-v1'))}catch{}if(!model||model.version!==1)model=createModel();
model.revision ||= 1;
const loadLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}};
let savedScenarios=loadLocal('northworks-snapshots',[]);if(!Array.isArray(savedScenarios))savedScenarios=[];
let resultRevision=null,zoom=16,operation=0,inspectorOpen=false;
let result=null,topic='capacity',mode='configure',scene=0,guide=false,selected=model.orders[0].id,baseline=loadLocal('northworks-comparison',null),undo=[],preview=null,busy=false,error='',requestId=0,drag=null;
let worker=new Worker(new URL('./worker.js?v=17',import.meta.url),{type:'module'});
let pending=null,queued=null;
worker.onerror=()=>{busy=false;pending=null;queued=null;error='Scheduler stopped. Reload to restart; inputs are saved.';status();};
function persist(){localStorage.setItem('northworks-v1',JSON.stringify(model));}
function request(m=model,isPreview=false){error='';const item={id:++requestId,model:structuredClone(m),isPreview};busy=true;if(pending){queued=item;}else send(item);status();}
function send(item){pending=item;worker.postMessage(item);}
worker.onmessage=({data})=>{const current=pending;pending=null;if(data.id===requestId){error=data.error||'';if(!error){if(current.isPreview)preview=data.result;else {result=data.result;resultRevision=current.model.revision;preview=null;}}busy=false;renderChart();status();}if(queued){const next=queued;queued=null;send(next);}};
function fresh(){return result&&!busy&&!error&&!preview&&resultRevision===model.revision;}
function status(){for(const id of ['export','baseline']){const b=document.getElementById(id);if(b)b.disabled=!fresh();}document.querySelector('#chart')?.classList.toggle('outdated',!!result&&!preview&&resultRevision!==model.revision);const el=document.querySelector('#status');if(el)el.textContent=error|| (busy?'Updating schedule · previous result outdated':preview?'Live trial · release to apply':`Revision ${model.revision} · ${fresh()?'current result':'no current result'}`);const search=document.querySelector('#searchStats');if(search&&result)search.textContent=`${(preview||result).search.trials} trials · ${(preview||result).search.accepted} improvements · ${(preview||result).search.ms.toFixed(1)} ms`}
function change(fn){undo.push(structuredClone(model));if(undo.length>25)undo.shift();const revision=(model.revision||0)+1;fn();model.revision=revision;persist();preview=null;render();request();}
const opts=(obj,current)=>Object.entries(obj).map(([v,n])=>`<option value="${esc(v)}" ${String(current)===v?'selected':''}>${esc(n)}</option>`).join('');
function inspector(){
 if(topic==='supply')return `${(model.materials||[]).map(m=>`<label>${esc(m.name)} available (hours from D1 06:00)<input data-material="${m.id}" type="number" min="0" max="480" value="${m.ready}"></label>`).join('')}${(model.skills||[]).map(s=>`<label>${esc(s.name)} · concurrent people<input data-skill="${s.id}" type="number" min="1" max="20" step="1" value="${s.count}"></label>`).join('')}<p class="note">Receipt time blocks the linked operation. One person is reserved during each operation requiring that skill. Customer policies are not imported.</p>`;
 if(topic==='scope')return `<button id="rebuildScenario">Build another scenario</button><p class="note">Source mapping at scenario creation. Current values and subsequent edits are shown in the workspace and comparison.</p>${(model.projection||[]).map(p=>`<details><summary>${esc(p.name)} · ${esc(p.status)}</summary><p>${esc(p.detail)}</p></details>`).join('')}`;
 if(topic==='legacy-scope')return `<label>Industry context<select id="industry">${opts({'Process manufacturing':'Process manufacturing','Discrete manufacturing':'Discrete manufacturing'},model.industry)}</select></label><div class="scope-picks">${['APS','MOM','SCM'].map(v=>`<label><input type="checkbox" data-scope="${v}" ${model.scope.includes(v)?'checked':''}>${v}<small>${v==='APS'?'Executable model':'Blueprint scope'}</small></label>`).join('')}</div><p class="note">This first rewrite implements the APS slice. Broader MOM/SCM configuration remains a blueprint requirement.</p>`;
 if(topic==='capacity')return `<label>Daily working window<select id="hours">${opts({8:'One shift · 8 hours',16:'Two shifts · 16 hours',24:'Continuous · 24 hours',[model.calendar.hours]:`${model.calendar.hours} working hours`},model.calendar.hours)}</select></label><p class="note">Every day starts at 06:00. Processing stays within one working window.</p>${model.resources.map(r=>`<div class="resource"><span class="resource-dot"></span><strong>${esc(r.name)}</strong><small>${esc(model.orders[0].operations.find(o=>o.group===r.group)?.name||r.group)}</small></div>`).join('')}`;
 if(topic==='cleaning')return `<label class="switch"><input type="checkbox" id="cleanEnabled" ${model.cleaning.enabled?'checked':''}>Sequence-dependent cleaning</label><p class="note">Hours from current family (row) to next family (column). Last run: no terminal clean.</p><table class="matrix"><tr><th>From ↓ / To →</th>${'ABC'.split('').map(f=>`<th>${f}</th>`).join('')}</tr>${'ABC'.split('').map(f=>`<tr><th>${f}</th>${'ABC'.split('').map(t=>`<td><input aria-label="Cleaning ${f} to ${t}" data-matrix="${f}${t}" type="number" min="0" max="8" step="0.5" value="${model.cleaning.matrix[f][t]}"></td>`).join('')}</tr>`).join('')}</table><label>Feedback search effort<select id="budget">${opts({20:'Quick · 20 trials',80:'Standard · 80 trials',200:'Deep · 200 trials'},model.budget)}</select></label><p class="note">Search revisits choices in the background. Objective: cleaning, then lateness, then completion time. It is bounded local search.</p>`;
 if(topic==='tank')return `<label>Capacity per family tank (L)<input id="tankCapacity" type="number" min="1" max="10000" value="${model.tank.capacity}"></label><label>Volume per order (L)<input id="batch" type="number" min="1" max="1000" value="${model.tank.batch}"></label><p class="note">One tank per family. Constant inflow during blending and outflow during filling. No flow during cleaning. Red indicates capacity exceeded.</p>`;
 const order=model.orders.find(o=>o.id===selected)||model.orders[0];return `<label>Order<select id="order">${opts(Object.fromEntries(model.orders.map(o=>[o.id,`${o.id} · ${o.family}`])),order.id)}</select></label>${[['release','Release (hours)',0,240],['due','Due (hours)',0,480],['priority','Priority (5 = highest)',1,5]].map(([k,n,min,max])=>`<label>${n}<input data-order-field="${k}" type="number" min="${min}" max="${max}" value="${order[k]}"></label>`).join('')}${operationEditor(order)}<p class="note">Hours from D1 06:00. Synthetic order; edit the scenario assumptions here.</p>`;
}
function render(){
 if(topic==='tank'&&model.tank.enabled===false)topic='supply';
 const t=topics.find(t=>t.id===topic);
 document.querySelector('#app').innerHTML=`<aside class="rail"><div class="brand"><span class="brandmark">N</span><div>NORTHWORKS<small>Manufacturing model studio</small></div></div><div class="rail-label">MODEL WORKSPACE</div>${topics.filter(t=>t.id!=='tank'||model.tank.enabled!==false).map((t,i)=>`<button class="topic ${topic===t.id?'active':''}" data-topic="${t.id}">${t.name}</button>`).join('')}<div class="rail-bottom"><span class="green-dot"></span> Local working model<p>Version 01 · APS foundation</p><button id="export">Export scenario + result</button><button id="scenarioLibrary">Saved scenarios (${savedScenarios.length})</button></div></aside><main><header><div><span class="eyebrow">${esc(model.industry)}</span><h1>${esc(model.name)}</h1></div><div class="header-actions"><button id="toggleInspector">${inspectorOpen?"Hide controls":"Edit "+esc(t.name.toLowerCase())}</button><button id="implementationHome">Implementation map</button><button id="undo" ${undo.length?'':'disabled'}>Undo</button><button id="reset">Build scenario</button></div></header><div class="run-status" id="status" role="status"></div><section class="workspace ${inspectorOpen?'editing':''}"><aside class="inspector"><span class="eyebrow">${t.tag}</span><h2>${t.name}</h2>${inspector()}<button class="guide-button" id="guide">${guide?'Show whole chart':'Highlight what matters'}</button></aside><div class="canvas"><div class="canvas-top"><div><span class="eyebrow">${mode==='experiment'?'WHAT-IF WORKBENCH':'LIVE MODEL'}</span><h2>Orders and delivery promises</h2></div><label>Comparison name<input id="comparisonName" placeholder="Before changing shifts"></label><button id="baseline">Save comparison</button></div><div class="rulebar"><label>Dispatch rule<select id="rule">${opts(rules,model.rule)}</select></label><label>Time scale<select id="zoom">${opts({8:"Overview",16:"Standard",30:"Detailed"},zoom)}</select></label><div class="search-stat" id="searchStats"></div></div><div id="metrics"></div><div class="chart-caption"><span>Resource schedule</span><small>Drag or select to edit · solid = processing · violet = cleaning · dotted = waiting</small></div><div id="chart"></div><p class="note" id="detail"></p><div id="orderConsequences"></div><div class="canvas-foot"><span>All charts share the same time axis.</span><span>Finite capacity · synthetic demand</span></div></div></section></main>`;
 document.querySelector('#toggleInspector').onclick=()=>{inspectorOpen=!inspectorOpen;render();};
 document.querySelector('#implementationHome').onclick=()=>{location.hash='';mountJourney({openLab});};
 document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{topic=b.dataset.topic;inspectorOpen=true;scene=0;render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;guide=mode==='explain';scene=0;render()});
 const on=(id,fn)=>document.querySelector('#'+id)?.addEventListener('change',e=>{if(e.target.reportValidity())change(()=>fn(e.target));});
 on('hours',e=>model.calendar.hours=+e.value);on('industry',e=>model.industry=e.value);on('budget',e=>model.budget=+e.value);on('tankCapacity',e=>model.tank.capacity=Math.max(1,Math.min(10000,+e.value||1)));on('batch',e=>model.tank.batch=Math.max(1,Math.min(1000,+e.value||1)));on('cleanEnabled',e=>model.cleaning.enabled=e.checked);on('rule',e=>{model.rule=e.value;if(['clean','search'].includes(e.value))model.cleaning.enabled=true;});
 document.querySelectorAll('[data-matrix]').forEach(e=>e.onchange=()=>change(()=>model.cleaning.matrix[e.dataset.matrix[0]][e.dataset.matrix[1]]=Math.max(0,Math.min(8,+e.value||0))));
 document.querySelectorAll('[data-scope]').forEach(e=>e.onchange=()=>change(()=>model.scope=e.checked?[...model.scope,e.dataset.scope]:model.scope.filter(v=>v!==e.dataset.scope)));
 document.querySelector('#order')?.addEventListener('change',e=>{selected=e.target.value;operation=0;render()});document.querySelectorAll('[data-order-field]').forEach(e=>e.onchange=()=>change(()=>model.orders.find(o=>o.id===selected)[e.dataset.orderField]=Math.max(+e.min,Math.min(+e.max,+e.value||0))));
 document.querySelector('#guide').onclick=()=>{guide=!guide;scene=0;render()};document.querySelector('#guideNext')?.addEventListener('click',()=>{if(scene===2)guide=false;else scene++;render()});document.querySelector('#baseline').onclick=()=>{if(fresh()){baseline=snapshot(model,result,document.querySelector('#comparisonName').value.trim()||`Revision ${model.revision}`);localStorage.setItem('northworks-comparison',JSON.stringify(baseline));savedScenarios.push(baseline);localStorage.setItem('northworks-snapshots',JSON.stringify(savedScenarios));document.querySelector('#scenarioLibrary').textContent=`Saved scenarios (${savedScenarios.length})`;renderChart()}};document.querySelector('#undo').onclick=()=>{const revision=model.revision+1;model=undo.pop();model.revision=revision;persist();render();request()};document.querySelector('#reset').onclick=()=>showProjection(model.implementation||{});
 document.querySelector('#rebuildScenario')?.addEventListener('click',()=>showProjection(model.implementation||{}));
 document.querySelector('#scenarioLibrary').onclick=showScenarioLibrary;
 bindOperationEditor();
 document.querySelector('#zoom').onchange=e=>{zoom=+e.target.value;renderChart();};
 for(const [selector,fn] of [['[data-material]',e=>model.materials.find(m=>m.id===e.dataset.material).ready=+e.value],['[data-skill]',e=>model.skills.find(s=>s.id===e.dataset.skill).count=+e.value]])document.querySelectorAll(selector).forEach(e=>e.onchange=()=>{if(e.reportValidity())change(()=>fn(e));});
 document.querySelector('#export').onclick=()=>{if(!fresh())return;const blob=new Blob([JSON.stringify(snapshot(model,result,model.name),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='northworks-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 renderChart();status();
}
function renderChart(){
 if(!result)return;const r=preview||result;const root=document.querySelector('#chart');if(!root)return;const left=root.scrollLeft;
 const horizon=Math.ceil(Math.max(72,r.end+4)/24)*24,width=horizon*zoom;
 document.querySelector('#metrics').innerHTML=[['On time',`${model.orders.length-r.late} / ${model.orders.length}`],['Cleaning',`${r.clean.toFixed(1)} h`],['Total lateness',`${r.tardy.toFixed(1)} h`]].map(([name,value])=>`<div><small>${name}</small><strong>${value}</strong></div>`).join('')+(baseline?.result?`<p>${esc(baseline.name)}${baseline.model?.caseId!==model.caseId?' · different operating case':''}: cleaning ${baseline.result.clean.toFixed(1)} → ${r.clean.toFixed(1)} h · late orders ${baseline.result.late} → ${r.late}</p>`:'');
 if(drag&&preview){
  root.firstElementChild.style.width=`${width+180}px`;root.querySelector('.axis>div').innerHTML=Array.from({length:horizon/6},(_,i)=>`<span style="left:${i*6*zoom}px">${time(i*6)}</span>`).join('');root.querySelectorAll('.track').forEach(t=>t.style.width=`${width}px`);root.querySelector('#liquidAxes').innerHTML=renderSecondary(r,width);
  root.querySelectorAll('.trial-bar').forEach(el=>el.remove());
  for(const op of r.ops){const track=root.querySelector(`[data-resource="${op.resource}"]`);const ghost=document.createElement('span');ghost.className=`trial-bar family-${op.family}`;ghost.style.left=`${op.start*zoom}px`;ghost.style.width=`${(op.end-op.start)*zoom}px`;ghost.textContent=`${op.order.slice(3)} · ${op.family}`;track.appendChild(ghost);}
  document.querySelector('#detail').textContent=`Live trial: ${r.clean.toFixed(1)} h cleaning, ${r.late} late orders. Release to apply.`;
  renderConsequences(r);status();return;
 }
 root.className=`timeline ${preview?'preview':''} ${guide?'guided':''}`;
 root.innerHTML=`<div style="width:${width+180}px"><div class="axis"><strong>Resource</strong><div>${Array.from({length:horizon/6},(_,i)=>`<span style="left:${i*6*zoom}px">${time(i*6)}</span>`).join('')}</div></div>${model.resources.map((resource,i)=>`<div class="lane ${guide&&((topic==='capacity'&&i===0)||(topic==='cleaning'))?'focus':''}"><strong>${esc(resource.name)}${guide&&i===0?`<small class="inline-cue">${topic==='cleaning'?'Purple = cleaning':'Open time only'}</small>`:""}</strong><div class="track" data-resource="${resource.id}" style="width:${width}px;background-size:${24*zoom}px 100%;--open:${model.calendar.hours/24*100}%">${r.ops.filter(o=>o.resource===resource.id).map(o=>`<button draggable="false" aria-label="${esc(o.order)} · ${o.family}" data-key="${o.key}" class="bar family-${o.family} ${r.orders.find(x=>x.id===o.order).tardy?'late':''}" style="left:${o.start*zoom}px;width:${(o.end-o.start)*zoom}px" title="${o.order}: output ${time(o.processEnd)}, resource free ${time(o.end)}"><span class="processing" style="width:${(o.processEnd-o.start)/(o.end-o.start)*100}%">${esc(o.order.replace(/^WO-/,''))}</span>${o.clean?`<i style="left:${(o.cleanStart-o.start)/(o.end-o.start)*100}%;width:${o.clean/(o.end-o.start)*100}%"></i>`:''}</button>`).join('')}</div></div>`).join('')}<div id="liquidAxes">${renderSecondary(r,width)}</div></div>`;root.scrollLeft=left;
 renderConsequences(r);
 document.querySelector('#detail').textContent=preview?'Live trial. Release to apply, Escape to cancel.':`Latest result: ${time(r.end)} resource completion. ${model.rule==='search'?`${r.search.accepted} search improvements accepted.`:''}`;
 root.querySelectorAll('.bar').forEach(b=>{
  let origin=null,suppressClick=false;
  b.onclick=()=>{if(suppressClick){suppressClick=false;return;}selected=b.dataset.key.split(':')[0];operation=+b.dataset.key.split(':')[1];inspectorOpen=true;topic='orders';render();};
  b.onpointerdown=e=>{if(e.button!==0||!fresh())return;origin={x:e.clientX,y:e.clientY,id:e.pointerId};b.setPointerCapture(e.pointerId);};
  b.onpointermove=e=>{
   if(!origin)return;
   if(!drag){if(Math.hypot(e.clientX-origin.x,e.clientY-origin.y)<4)return;const op=result.ops.find(o=>o.key===b.dataset.key);drag={key:op.key,order:op.order,offset:origin.x-b.getBoundingClientRect().left,group:model.resources.find(x=>x.id===op.resource).group};suppressClick=true;}
   const track=document.elementFromPoint(e.clientX,e.clientY)?.closest('.track');
   if(!track||model.resources.find(x=>x.id===track.dataset.resource)?.group!==drag.group){drag.valid=false;return;}
   drag.valid=true;
   const start=Math.max(0,Math.round((e.clientX-track.getBoundingClientRect().left-drag.offset)/zoom*2)/2),signature=`${track.dataset.resource}:${start}`;
   if(drag.signature===signature)return;drag.signature=signature;drag.move={order:drag.order,resource:track.dataset.resource,start};
   const m=structuredClone(model);delete m.moves[drag.key];m.moves[drag.key]=drag.move;request(m,true);
  };
  const finish=cancel=>{origin=null;if(!drag)return;const d=drag;drag=null;if(!cancel&&d.valid&&d.move){change(()=>{delete model.moves[d.key];model.moves[d.key]=d.move;});}else{requestId++;queued=null;preview=null;busy=false;renderChart();status();}};
  b.onpointerup=()=>finish(false);b.onpointercancel=()=>finish(true);
 });
 status();
}
function openLab(configuration){if(configurationKey(configuration)!==model.sourceKey){showProjection(configuration||{});return;}location.hash='experiment';render();request();}
function operationEditor(order){
 const op=order.operations[operation]||order.operations[0],key=`${order.id}:${operation}`,move=model.moves[key],scheduled=result?.ops.find(o=>o.key===key);
 return `<label>Operation<select id="operation">${opts(Object.fromEntries(order.operations.map((o,i)=>[i,o.name||`Operation ${i+1}`])),operation)}</select></label><label>Processing hours<input id="duration" type="number" min="0.5" max="24" step="0.5" value="${op.hours}"></label><label>Resource<select id="moveResource">${opts(Object.fromEntries(model.resources.filter(r=>r.group===op.group).map(r=>[r.id,r.name])),move?.resource||scheduled?.resource)}</select></label><label>Earliest start (hours from D1 06:00)<input id="moveStart" type="number" min="0" max="480" step="0.5" value="${move?.start||scheduled?.start||0}"></label><button id="applyMove">Apply move</button><button id="clearMove">Release position</button><p class="note">Reserves this resource and earliest start. This whole order gets priority; capacity and dependencies can push its operations later.</p>`;
}
function bindOperationEditor(){
 document.querySelector('#operation')?.addEventListener('change',e=>{operation=+e.target.value;render();});
 document.querySelector('#duration')?.addEventListener('change',e=>{if(e.target.reportValidity())change(()=>model.orders.find(o=>o.id===selected).operations[operation].hours=+e.target.value);});
 document.querySelector('#applyMove')?.addEventListener('click',()=>{const start=document.querySelector('#moveStart'),resource=document.querySelector('#moveResource').value;if(!start.reportValidity())return;change(()=>{const key=`${selected}:${operation}`;delete model.moves[key];model.moves[key]={order:selected,resource,start:+start.value};});});
 document.querySelector('#clearMove')?.addEventListener('click',()=>change(()=>delete model.moves[`${selected}:${operation}`]));
}
function renderSecondary(r,width){
 if(model.tank.enabled===false)return renderPeople(r,width);
 return `<div class="tank-heading">Liquid inventory · liters <small>Diagnostic; does not block scheduling</small></div>${[...'ABC'].map(f=>{const pts=tankProfile(model,r,f),peak=Math.max(model.tank.capacity,...pts.map(p=>p.value)),y=v=>70-v/peak*48,path=pts.map((p,i)=>`${i?'L':'M'}${p.t*zoom},${y(p.value)}`).join(' ')+` H${width}`;return `<div class="tank-row"><strong>Buffer ${f}<small>${Math.max(...pts.map(p=>p.value)).toFixed(0)} L peak</small><small>Limit ${model.tank.capacity} L</small></strong><svg width="${width}" height="88" role="img" aria-label="Buffer ${f} volume in liters"><line x1="0" x2="${width}" y1="${y(model.tank.capacity)}" y2="${y(model.tank.capacity)}" stroke="#a94f61" stroke-dasharray="4 4"/><text x="4" y="${y(model.tank.capacity)-4}" font-size="11">${model.tank.capacity} L</text><text x="4" y="85" font-size="11">0 L</text><path d="${path}" fill="none" stroke="${pts.some(p=>p.value>model.tank.capacity)?'#b23e55':'#347f6d'}" stroke-width="2"/></svg></div>`;}).join('')}`+renderPeople(r,width);
}
function renderPeople(r,width){return (model.skills||[]).map(s=>{const pts=skillProfile(model,r,s.id),top=Math.max(s.count,...pts.map(p=>p.demand)),y=v=>65-v/top*45,path=pts.map((p,i)=>`${i?'L':'M'}${p.t*zoom},${y(p.demand)}`).join(' ')+` H${width}`;return `<div class="tank-row"><strong>${esc(s.name)}<small>${s.count} people available</small></strong><svg width="${width}" height="80" role="img" aria-label="${esc(s.name)} demand versus available headcount"><line x1="0" x2="${width}" y1="${y(s.count)}" y2="${y(s.count)}" stroke="#a57a37" stroke-dasharray="4 4"/><text x="4" y="15" font-size="11">${s.count} people</text><path d="${path}" fill="none" stroke="#536cab" stroke-width="2"/><text x="4" y="78" font-size="11">0 people</text></svg></div>`;}).join('');}
function renderConsequences(r){
 const el=document.querySelector('#orderConsequences');if(!el)return;
 el.innerHTML=`<details><summary>Delivery consequences · ${r.late} late orders</summary><table class="results-table"><tr><th>Order</th><th>Promise</th><th>Completion</th><th>Late</th><th>Change</th></tr>${r.orders.map(o=>{const prior=baseline?.model?.caseId===model.caseId?baseline?.result?.orders.find(x=>x.id===o.id):null;return `<tr><td>${esc(o.id)}</td><td>${time(model.orders.find(x=>x.id===o.id).due)}</td><td>${time(o.completion)}</td><td>${o.tardy.toFixed(1)} h</td><td>${prior?`${(o.completion-prior.completion).toFixed(1)} h`:'—'}</td></tr>`;}).join('')}</table></details>${baseline?.model?`<details><summary>Changed inputs since ${esc(baseline.name)}</summary><table class="results-table"><tr><th>Input</th><th>Saved</th><th>Current</th></tr>${inputDifferences(baseline.model,model).map(d=>`<tr><td>${esc(d.field)}</td><td>${esc(d.before)}</td><td>${esc(d.after)}</td></tr>`).join('')||'<tr><td colspan="3">No input changes</td></tr>'}</table></details>`:''}`;
}
function showScenarioLibrary(){
 document.querySelector('#app').innerHTML=`<div class="projection"><button id="backToScenario">← Working scenario</button><h1>Saved scenarios</h1><p>Each record includes its inputs, result, date and revision. Restoring inputs recalculates the schedule.</p><label>Import a scenario JSON<input id="importScenario" type="file" accept=".json,application/json"></label><p id="importStatus" role="status"></p><table class="results-table"><tr><th>Scenario</th><th>Revision / date</th><th>Outcome</th><th>Use</th></tr>${savedScenarios.map((s,i)=>`<tr><td>${esc(s.name)}</td><td>${s.revision} · ${esc(s.createdAt?.slice(0,10))}</td><td>${s.result?.late??'—'} late · ${s.result?.clean?.toFixed(1)??'—'} h cleaning</td><td><button data-compare="${i}">Compare</button><button data-restore="${i}">Restore inputs</button></td></tr>`).join('')||'<tr><td colspan="4">Save a named comparison in the workspace to keep a scenario.</td></tr>'}</table></div>`;
 document.querySelector('#backToScenario').onclick=()=>{render();if(!fresh())request();};
 document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{baseline=savedScenarios[+b.dataset.compare];localStorage.setItem('northworks-comparison',JSON.stringify(baseline));render();if(!fresh())request();});
 const restore=m=>{localStorage.setItem('northworks-previous',JSON.stringify(model));const revision=model.revision+1;undo.push(structuredClone(model));model=m;model.revision=revision;selected=model.orders[0].id;operation=0;result=null;preview=null;persist();render();request();};
 document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{try{restore(validateScenario(savedScenarios[+b.dataset.restore]));}catch(e){document.querySelector('#importStatus').textContent=e.message;}});
 document.querySelector('#importScenario').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('Use a scenario file smaller than 5 MB.');restore(validateScenario(JSON.parse(await file.text())));}catch(error){document.querySelector('#importStatus').textContent=error.message;}};
}
function showProjection(configuration){
 let caseId=configuration.referenceCase||caseFor(configuration);location.hash='experiment';
 const draw=()=>{const projected=projectScenario(configuration,caseId);document.querySelector('#app').innerHTML=`<div class="projection"><button id="backMap">← Implementation map</button><h1>Build a working scenario</h1><p>Choose a reference process and inspect how the implementation decisions enter the experiment.</p><label>Reference process<select id="case">${opts(Object.fromEntries(Object.entries(cases).map(([id,c])=>[id,c.name])),caseId)}</select></label><p>${esc(cases[caseId].question)}</p><table class="results-table"><tr><th>Decision</th><th>Use in this run</th><th>Applied assumptions</th></tr>${projected.projection.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.status)}</td><td>${esc(x.detail)}</td></tr>`).join('')}</table><button class="primary" id="build">Build scenario</button><button id="resume">Resume saved scenario</button><button id="restorePrevious" ${localStorage.getItem('northworks-previous')?'':'disabled'}>Restore previous scenario</button></div>`;
 document.querySelector('#case').onchange=e=>{caseId=e.target.value;draw();};
 const start=()=>{selected=model.orders[0].id;operation=0;topic='capacity';inspectorOpen=false;result=null;preview=null;baseline=null;localStorage.removeItem('northworks-comparison');undo=[];persist();render();request();};
 document.querySelector('#build').onclick=()=>{localStorage.setItem('northworks-previous',JSON.stringify(model));model=projected;start();};
 document.querySelector('#resume').onclick=()=>{render();request();};
 document.querySelector('#restorePrevious').onclick=()=>{const previous=JSON.parse(localStorage.getItem('northworks-previous'));localStorage.setItem('northworks-previous',JSON.stringify(model));model=previous;start();};
 document.querySelector('#backMap').onclick=()=>{location.hash='';mountJourney({openLab});};};draw();
}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){drag=null;requestId++;queued=null;preview=null;busy=false;renderChart();status();}});
topics.push({id:'supply',name:'Materials & people',tag:'Availability',title:'What must be ready to run?',text:'Scenario receipt times and skill headcount affect the consuming operation.'});
if(location.hash==='#experiment')showProjection(JSON.parse(localStorage.getItem('implementationos-installer-v2')||'{}'));else mountJourney({openLab});
