// Shared, deterministic worked model. Quantities are synthetic units.
export const domains=[
 {id:'sop',name:'S&OP',title:'Balance demand and supply',sub:'Agree a monthly volume plan before detailed scheduling.',outputs:['Demand consensus','Capacity gap','Supply plan'],depends:['intent']},
 {id:'plm',name:'PLM',title:'Control the product revision',sub:'Choose the effective BOM revision and see its material impact.',outputs:['Effective revision','BOM quantities','Change effectivity'],depends:['intent']},
 {id:'lims',name:'LIMS',title:'Test a lot against its specification',sub:'Record a sample result and distinguish testing from release authority.',outputs:['Sample result','Specification check','Quality handoff'],depends:['plm']},
 {id:'qms',name:'QMS',title:'Decide whether a lot can be used',sub:'Connect laboratory evidence, investigation and disposition.',outputs:['Lot disposition','Held inventory','Corrective action'],depends:['lims']},
 {id:'mrp',name:'MRP',title:'Net requirements into planned supply',sub:'Explode the effective BOM, net usable stock and offset lead time.',outputs:['Net requirements','Planned receipts','Release dates'],depends:['sop','plm','qms']}
];
export const defaults={sop:{enabled:false,demand:1200,capacity:1000,opening:100,approved:false},plm:{enabled:false,revision:'B',effective:2,a:2,b:3},lims:{enabled:false,result:98,lower:95,upper:105,complete:false},qms:{enabled:false,lot:300,disposition:'hold',owner:'',action:''},mrp:{enabled:false,demand:1000,stock:400,receipts:100,safety:50,lot:100,lead:2,due:4}};
export function moduleInputs(state={}){return Object.fromEntries(domains.map(d=>[d.id,{...defaults[d.id],...state.businessModules?.[d.id]}]));}
export function calculateModules(state={}){
 const x=moduleInputs(state),s=x.sop,p=x.plm,l=x.lims,q=x.qms,m=x.mrp;
 const supply=Math.min(s.capacity,Math.max(0,s.demand-s.opening)),backlog=Math.max(0,s.demand-s.opening-supply),closing=Math.max(0,s.opening+supply-s.demand);
 const tested=l.enabled&&l.complete,pass=tested&&l.lower<=l.upper&&l.result>=l.lower&&l.result<=l.upper;
 const released=q.enabled&&q.disposition==='release'&&pass;
 const demand=s.enabled?(s.approved?supply:0):m.demand,blocked=s.enabled&&!s.approved;
 const revision=p.enabled&&p.revision==='B'&&m.due>=p.effective?'B':'A',per=p.enabled?(revision==='B'?p.b:p.a):2;
 const usable=Math.max(0,m.stock-(q.enabled?Math.min(m.stock,q.lot):0))+(released?Math.min(m.stock,q.lot):0);
 const gross=demand*per,net=Math.max(0,gross+m.safety-usable-m.receipts),receipt=blocked?0:Math.ceil(net/m.lot)*m.lot,release=m.due-m.lead;
 return {sop:{supply,backlog,closing},lims:{tested,pass,status:!tested?'Awaiting completed test':pass?'Within specification':'Outside specification'},qms:{released,held:q.enabled&&!released?Math.min(m.stock,q.lot):0,status:released?'Released':q.disposition==='reject'?'Rejected':q.disposition==='release'?'Release blocked: passing completed LIMS evidence required':'On hold'},mrp:{blocked,demand,revision,per,usable,gross,net,receipt,release,closing:usable+m.receipts+receipt-gross}};
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const numeric=(id,key,label,value,min=0,max=100000)=>`<label>${label}<input data-module="${id}" data-field="${key}" type="number" min="${min}" max="${max}" step="1" value="${value}"></label>`;
const check=(id,key,label,value)=>`<label class="module-check"><input data-module="${id}" data-field="${key}" type="checkbox" ${value?'checked':''}>${label}</label>`;
const select=(id,key,label,value,choices)=>`<label>${label}<select data-module="${id}" data-field="${key}">${choices.map(([v,n])=>`<option value="${v}" ${v===value?'selected':''}>${n}</option>`).join('')}</select></label>`;
const results=rows=>`<div class="case-outcomes">${rows.map(([k,v])=>`<div><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div>`;
export function moduleBody(id,state){
 const x=moduleInputs(state),r=calculateModules(state),v=x[id];let controls='',view='',note='';
 if(id==='sop'){controls=numeric(id,'demand','Monthly demand (finished units)',v.demand)+numeric(id,'capacity','Monthly supply capacity (units)',v.capacity)+numeric(id,'opening','Opening finished stock (units)',v.opening)+check(id,'approved','Approve this volume for the MRP trial',v.approved);view=results([['Planned production',r.sop.supply],['Uncovered demand',r.sop.backlog],['Closing stock',r.sop.closing]])+`<div class="volume-balance"><span style="width:${Math.min(100,(v.opening+r.sop.supply)/Math.max(1,v.demand)*100)}%">${Math.min(v.demand,v.opening+r.sop.supply)} / ${v.demand} covered</span></div>`;note='One monthly bucket. Approval passes planned production to the MRP trial; uncovered demand remains visible. Financial reconciliation and multilevel capacity are outside this sketch.';}
 if(id==='plm'){controls=select(id,'revision','Approved revision',v.revision,[['A','A · existing'],['B','B · changed design']])+numeric(id,'effective','Revision B effective from week',v.effective,1,52)+numeric(id,'a','Revision A · component units per product',v.a,1)+numeric(id,'b','Revision B · component units per product',v.b,1);view=results([['MRP requirement week',x.mrp.due],['Effective revision',r.mrp.revision],['Component units per product',r.mrp.per]]);note='Worked product: dosing kit; component: seal. Revision B applies from its effective week only when approved. This is a single-level BOM; CAD, documents and formal engineering approval remain implementation contracts.';}
 if(id==='lims'){controls=numeric(id,'result','Assay result (%)',v.result,0,200)+numeric(id,'lower','Lower limit (%)',v.lower,0,200)+numeric(id,'upper','Upper limit (%)',v.upper,0,200)+check(id,'complete','Test complete and result reviewed',v.complete);view=results([['Sample LOT-001',r.lims.status],['Specification',`${v.lower}–${v.upper}%`],['Observed',`${v.result}%`]]);note='One assay for LOT-001. A passing result is evidence for QMS, not automatic lot release. Instruments, sampling plans and laboratory audit trails are not connected.';}
 if(id==='qms'){controls=numeric(id,'lot','LOT-001 quantity included in MRP stock',v.lot)+select(id,'disposition','Lot disposition',v.disposition,[['hold','Hold'],['release','Release'],['reject','Reject']])+`<label>Investigation owner<input data-module="qms" data-field="owner" value="${esc(v.owner)}"></label><label>Containment / corrective action<textarea data-module="qms" data-field="action">${esc(v.action)}</textarea></label>`;view=results([['Disposition effect',r.qms.status],['Unavailable component stock',r.qms.held],['Laboratory evidence',r.lims.status]]);note='LOT-001 is part of MRP opening stock, never additional stock. Release requires completed, passing LIMS evidence. Reject and hold both exclude stock. Corrective actions are recorded, not workflow-certified.';}
 if(id==='mrp'){controls=numeric(id,'demand','Independent production demand (S&OP off)',v.demand)+numeric(id,'stock','Opening component stock, including held lot',v.stock)+numeric(id,'receipts','Firm receipts by requirement week',v.receipts)+numeric(id,'safety','Safety stock',v.safety)+numeric(id,'lot','Purchase lot multiple',v.lot,1)+numeric(id,'lead','Lead time (weeks)',v.lead,0,52)+numeric(id,'due','Requirement week',v.due,1,52);view=results([['Gross components',r.mrp.gross],['Usable stock',r.mrp.usable],['Planned receipt',r.mrp.receipt]])+`<table class="case-table"><tr><th>Source</th><th>Requirement</th><th>Release</th><th>Projected closing</th></tr><tr><td>${x.sop.enabled?'Approved S&OP production':'Independent demand'} · revision ${r.mrp.revision}</td><td>W${v.due}: ${r.mrp.demand} products × ${r.mrp.per}</td><td>${r.mrp.blocked?'Blocked: approve S&OP':r.mrp.receipt===0?'No planned order':r.mrp.release<1?'Past due · expedite required':`W${r.mrp.release}`}</td><td>${r.mrp.blocked?'Pending plan':r.mrp.closing}</td></tr></table>`;note='Single product, single component and one requirement bucket. Net = gross + safety − usable stock − firm receipts; round positive need to the purchase multiple. Planned receipts are proposals, not released purchase orders or APS operations.';}
 return `<section class="decision-context module-work"><div class="case-heading"><strong>Dosing kit · connected worked example</strong><small>Synthetic quantities · shared across these five modules</small></div><p class="trial-label">Worked trial · ${v.enabled?'In project scope':'Outside project scope'}</p>${!v.enabled?'<p>Preview only. Enable this module to apply it to connected trials.</p>':''}${view}<div class="contract-fields">${controls}</div><p>${note}</p><button id="exportModuleTrial">Export connected trial</button></section>`;
}
export function registerModules({state,steps,render}){
 for(const d of domains)steps.push({id:d.id,phase:d.name,nav:d.name,title:d.title,sub:d.sub,body:()=>moduleBody(d.id,state),attach:root=>{
 root.querySelectorAll('[data-module]').forEach(e=>e.onchange=()=>{if(!e.reportValidity())return;state.businessModules||={};state.businessModules[e.dataset.module]||={};state.businessModules[e.dataset.module][e.dataset.field]=e.type==='checkbox'?e.checked:e.type==='number'?+e.value:e.value;render();});
 root.querySelector('#exportModuleTrial').onclick=()=>{const data={version:1,kind:'connected-business-trial',createdAt:new Date().toISOString(),inputs:moduleInputs(state),results:calculateModules(state),provenance:'Synthetic worked example; no production orders released'},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='business-module-trial.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 }});
 const scope=steps.find(s=>s.id==='scope'),gate=scope.gate;scope.gate=()=>gate()||Object.values(state.businessModules||{}).some(v=>v.enabled);
}
