export const capabilityGroups=[
 {name:'Plan demand and supply',items:[{id:'sop',name:'S&OP',purpose:'Agree demand, supply and inventory targets',flow:'Consensus plan → master planning',area:'sop'},{id:'master',name:'Master planning',purpose:'Turn agreed volumes into a time-phased supply plan',flow:'Supply plan → MRP and APS',area:'master'},{id:'mrp',name:'MRP',purpose:'Determine material quantities and required dates',flow:'BOM + usable stock → planned supply',area:'mrp'},{id:'aps',name:'APS',purpose:'Schedule operations against finite capacity',flow:'Orders + constraints → resource schedule',area:'plant'}]},
 {name:'Define and assure the product',items:[{id:'plm',name:'PLM',purpose:'Control product definitions and engineering changes',flow:'Approved revisions → planning and production',area:'plm'},{id:'qms',name:'QMS',purpose:'Manage quality events, actions and disposition',flow:'Quality evidence → release or containment',area:'qms'},{id:'lims',name:'LIMS',purpose:'Manage samples, tests and laboratory results',flow:'Reviewed results → quality decisions',area:'lims'}]},
 {name:'Execute and respond',items:[{id:'mes',name:'Life sciences MES',purpose:'Design and execute a controlled electronic batch record',flow:'Master recipe → execution evidence → QA release',area:'mes'},{id:'dispatch',name:'Dispatch & execution',purpose:'Release work and reconcile shop-floor progress',flow:'Schedule → actuals → replanning',area:'execution'}]}
];
export const capabilities=capabilityGroups.flatMap(g=>g.items);
export function selectedCapabilities(s){return capabilities.filter(c=>c.id==='aps'?s.scope==='aps-ds':c.id==='master'?!!s.masterPlanning?.enabled:c.id==='dispatch'?!!s.dispatch?.enabled:!!s.businessModules?.[c.id]?.enabled);}
export function setCapability(s,id,on){if(id==='aps')s.scope=on?'aps-ds':null;else if(id==='master'){s.masterPlanning||={};s.masterPlanning.enabled=on;}else if(id==='dispatch'){s.dispatch||={};s.dispatch.enabled=on;}else{s.businessModules||={};s.businessModules[id]||={};s.businessModules[id].enabled=on;}}
export function areaApplies(id,s){const ids=new Set(selectedCapabilities(s).map(c=>c.id));if(['intent','validation','handoff'].includes(id))return true;if(['sop','mrp','plm','qms','lims','master'].includes(id))return ids.has(id);if(id==='execution')return ids.has('dispatch');if(id==='plant'||id==='constraints')return ids.has('aps');if(id==='product')return ['aps','mrp','plm','qms','lims','master'].some(x=>ids.has(x));return true;}
export function stepApplies(id,s){if(id.endsWith('-design'))return areaApplies(id.replace('-design',''),s);if(['sop','mrp','plm','qms','lims'].includes(id))return areaApplies(id,s);if(id.startsWith('master-'))return areaApplies('master',s);if(['dispatch-purpose','dispatch-control','execution'].includes(id))return areaApplies('execution',s);if(['calendar-gantt-intro','calendar','calendar-gantt-preview','bottleneck-intro','constraint','bottleneck-preview','areas','workcenters','tank-intro','volume-storage','tank-preview','transition-intro','transitions','transition-preview','workforce-intro','workforce','workforce-preview'].includes(id))return areaApplies('plant',s);if(id==='variant')return s.scope==='aps-ds';if(id.startsWith('attr-')||['bom','supplies'].includes(id)){const ids=new Set(selectedCapabilities(s).map(c=>c.id));if(ids.has('aps')||ids.has('plm'))return true;if(['attr-classification','attr-descriptor'].includes(id))return areaApplies('product',s);if(['attr-batchSerial','attr-quality'].includes(id))return ['qms','lims','mrp'].some(x=>ids.has(x));return ['mrp','master'].some(x=>ids.has(x));}return true;}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderScope(root,s,render){const selected=selectedCapabilities(s),ids=new Set(selected.map(c=>c.id));root.innerHTML=`<section class="unified-scope"><div class="scope-summary"><strong>${selected.length?selected.map(c=>c.name).join(' · '):'Choose the capabilities in this implementation'}</strong><span>${selected.length} selected</span></div>${capabilityGroups.map(g=>`<section class="capability-group"><h3>${g.name}</h3><div class="capability-grid">${g.items.map(c=>`<button type="button" class="capability-card ${ids.has(c.id)?'selected':''}" data-capability="${c.id}" aria-pressed="${ids.has(c.id)}"><span class="capability-title">${c.name}<span aria-hidden="true">${ids.has(c.id)?'✓':'+'}</span></span><span>${c.purpose}</span><small>${c.flow}</small></button>`).join('')}</div></section>`).join('')}<p class="scope-contract">Your journey includes the selected capabilities plus shared data, system ownership and validation. Connected capabilities can remain external; selecting one does not silently select the others.</p></section>`;root.querySelectorAll('[data-capability]').forEach(b=>b.onclick=()=>{setCapability(s,b.dataset.capability,!ids.has(b.dataset.capability));render();});}
