import {stepApplies,selectedCapabilities} from './capabilities.js?v=17';
import {cases,caseFor,projectScenario,configurationKey} from './scenarios.js?v=17';
import {schedule,tankProfile} from './engine.js?v=17';
import {time} from './model.js?v=17';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(head,rows)=>`<div class="case-table-wrap"><table class="case-table"><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const field=(key,label,value,min=0,max=480)=>`<label>${esc(label)}<input data-case-field="${key}" type="number" min="${min}" max="${max}" step="0.5" value="${value}"></label>`;
export function decisionState(state,id){const e=state.decisionEvidence?.[id];return !e?'Draft':e.key!==configurationKey(state)?'Needs re-review':'Reviewed';}
function scheduleTable(m,r){return table(['Resource','Order / operation','Processing','Machine free'],r.ops.map(o=>[m.resources.find(x=>x.id===o.resource).name,`${o.order} / ${m.orders.find(x=>x.id===o.order).operations[o.index].name}`,`${time(o.start)} – ${time(o.processEnd)}`,time(o.end)]));}
function spark(m,r,width=600){const horizon=Math.ceil(Math.max(48,r.end)/24)*24,scale=width/horizon;return `<svg class="case-schedule" viewBox="0 0 ${width+230} ${m.resources.length*42+40}" role="img" aria-label="Calculated resource schedule; time origin day one 06:00">${Array.from({length:horizon/24+1},(_,i)=>`<text x="${170+i*24*scale}" y="16">D${i+1} 06</text>`).join('')}${m.resources.map((asset,i)=>`<text x="0" y="${48+i*42}">${esc(asset.name)}</text>${r.ops.filter(o=>o.resource===asset.id).map(o=>`<g><title>${esc(o.order)}: ${time(o.start)}–${time(o.end)}</title><rect x="${170+o.start*scale}" y="${28+i*42}" width="${Math.max(1,(o.processEnd-o.start)*scale)}" height="25" rx="3" fill="#397d73"/>${(o.processEnd-o.start)*scale>25?`<text x="${173+o.start*scale}" y="${45+i*42}" style="fill:white;font-size:10px">${esc(o.order.replace(/^WO-/,''))}</text>`:''}${o.clean?`<rect x="${170+o.cleanStart*scale}" y="${28+i*42}" width="${o.clean*scale}" height="25" fill="#9463ab"/>`:''}</g>`).join('')}`).join('')}</svg>`;}
function experiment(topic,m){
 const before=structuredClone(m),after=structuredClone(m);
 let changed='';
 if(topic==='capacity'){before.calendar.hours=8;changed=`Only daily capacity changes: 8 → ${after.calendar.hours} hours.`;}
 if(topic==='transition'){before.cleaning.enabled=false;after.cleaning.enabled=true;changed='Only sequence-dependent cleaning changes: off → on. The A/B/C duration matrix is a scenario assumption.';}
 if(topic==='workforce'){before.skills.forEach(s=>s.count=4);changed=`Only specialist availability changes: 4 → ${after.skills[0].count} people.`;}
 if(topic==='bottleneck'){before.calendar.hours=24;changed=`Only daily capacity changes: 24 → ${after.calendar.hours} hours. Loading alone does not establish the delivery bottleneck.`;}
 if(topic==='tank'){before.tank.capacity=400;changed=`Only buffer capacity changes: 400 → ${after.tank.capacity} L. It is diagnostic, so scheduled dates stay unchanged.`;}
 const a=schedule(before),b=schedule(after),horizon=Math.ceil(Math.max(a.end,b.end)/24)*24;
 let visual=topic==='tank'?`<div class="case-pair">${[[before,a,'400 L reference'],[after,b,`${after.tank.capacity} L trial`]].map(([model,r,label])=>{const points=tankProfile(model,r,'A'),top=Math.max(400,...points.map(x=>x.value)),path=points.map((p,i)=>`${i?'L':'M'}${p.t/horizon*500},${130-p.value/top*110}`).join(' ');return `<div><h4>${label} · buffer A</h4><svg viewBox="0 0 520 155" role="img" aria-label="Continuous volume in liters"><line x1="0" x2="500" y1="${130-model.tank.capacity/top*110}" y2="${130-model.tank.capacity/top*110}" stroke="#a7485d" stroke-dasharray="4 4"/><path d="${path}" fill="none" stroke="#397d73" stroke-width="3"/><text x="0" y="150">D1 06:00 · 0 L</text><text x="330" y="150">D${horizon/24+1} 06:00</text><text x="0" y="15">${top.toFixed(0)} L</text></svg></div>`;}).join('')}</div>`:`<div class="case-pair">${[[before,a,'Reference'],[after,b,'Current trial']].map(([model,r,label])=>`<div><h4>${label}</h4>${spark(model,{...r,end:horizon})}</div>`).join('')}</div>`;
 if(topic==='bottleneck')visual+=table(['Resource','Work + clean','Available over horizon','Late orders using asset'],m.resources.map(r=>{const ops=b.ops.filter(o=>o.resource===r.id);return [r.name,`${ops.reduce((v,o)=>v+o.processEnd-o.start+o.clean,0).toFixed(1)} h`,`${horizon/24*m.calendar.hours} h`,[...new Set(ops.filter(o=>b.orders.find(x=>x.id===o.order).tardy>0).map(o=>o.order))].join(', ')||'None'];}));
 return `<p class="case-change">${changed} Same orders, routes, horizon and time scale.</p><div class="case-outcomes">${[['Cleaning',`${a.clean.toFixed(1)} → ${b.clean.toFixed(1)} h`],['Late orders',`${a.late} → ${b.late}`],['Total lateness',`${a.tardy.toFixed(1)} → ${b.tardy.toFixed(1)} h`]].map(([label,value])=>`<div><small>${label} · reference → trial</small><strong>${value}</strong></div>`).join('')}</div><div class="case-toggle"><button data-comparison="0" aria-pressed="false">Reference</button><button data-comparison="1" aria-pressed="true">Current trial</button><span>Teal: processing · purple: cleaning</span></div>${visual}<details><summary>Inspect operation times and assumptions</summary>${scheduleTable(after,b)}<p>All work starts from D1 06:00. Quantities and duration matrix are synthetic. Resource calendars repeat daily; no imported holidays.</p></details>`;
}
function topicOf(id){return id.startsWith('calendar-gantt')?'capacity':id.startsWith('bottleneck')?'bottleneck':id.startsWith('tank-')?'tank':id.startsWith('transition-')?'transition':id.startsWith('workforce-')?'workforce':null;}
function detailFor(id,state,m,def){
 const first=m.orders[0],inputs=state.scenarioInputs||{},rows=Object.entries(first).filter(([k])=>['id','product','quantity','unit','family','release','due'].includes(k));
 if(['architecture','execution','master-handoff','migration'].includes(id)){
  const contract=state.contracts?.[id]||{};
  const fields=id==='migration'?[['source','Current system'],['target','Target system'],['timing','Cutover / coexistence window'],['owner','Owner'],['key','Objects and keys affected'],['failure','Rollback / recovery']]:[['object','Business object'],['source','Producing system'],['target','Consuming system'],['key','Business key + revision field'],['timing','Trigger / frequency'],['owner','Data owner'],['failure','Failure / retry handling']];
  return `<details data-contract-details><summary>${id==='migration'?'Migration details':'Interface details'}</summary><div class="contract-fields">${fields.map(([key,label])=>`<label>${label}<input data-contract="${key}" value="${esc(contract[key]||'')}" placeholder="Not specified"></label>`).join('')}</div><p>Captured contract; no live system connection. Unknown fields remain visible for handoff.</p></details>`;
 }
 if(id==='workcenters')return m.resources.map(r=>`<label>${r.group==='blend'?def.route[0]:def.route[1]} asset<input data-asset-name="${r.id}" value="${esc(r.name)}"></label>`).join('')+'<p>These names carry into the scenario. Select required resource categories below.</p>';
 if(id==='attr-planning')return first.operations.map((op,i)=>`<label>${esc(op.name)} · processing hours<input data-route-hours="${i}" type="number" min="0.5" max="24" step="0.5" value="${op.hours}"></label>`).join('')+'<p>Applies to every reference order on this route. Actual product-specific rates and quantity scaling require customer records.</p>';
 if(id==='calendar')return field('hours','Daily working hours from 06:00',m.calendar.hours,4,24)+'<p>These exact hours are used by the worked case and scenario builder. Shift taxonomy and exception requirements remain below.</p>';
 if(id==='volume-storage')return m.tank.enabled?field('tankCapacity','Capacity per family buffer (L)',m.tank.capacity,1,10000)+field('batch','Volume per order (L)',m.tank.batch,1,1000):'<p>No product-liquid inventory applies to this reference process. Select a liquid case to explore vessel behavior.</p>';
 if(id==='workforce')return field('people',`${def.skill} · concurrent headcount`,m.skills[0].count,1,20)+table(['Demand','Quantity','Reservation'],[[def.route[1],'1 person per operation','Processing interval only']]);
 if(id==='supplies')return field('materialReady',`${def.materials[0]} receipt (hours from D1 06:00)`,m.materials[0].ready)+table(['Material','Consumes at','Policy'],[[def.materials[0],`${first.id} / ${def.route[0]}`,'Scenario receipt blocks operation; no stock allocation']]);
 if(id.startsWith('attr-')){const kinds={'attr-classification':['Family',first.family,'Groups cleaning transitions'],'attr-descriptor':['Description',first.product,'Display only; no timing effect'],'attr-planning':['Quantity',`${first.quantity} ${first.unit}`,'Sample route durations are explicit; quantity does not scale them'],'attr-variant':['Product option',first.family,'A/B/C are scenario families; customer BOM options remain requirements'],'attr-batchSerial':['Lot',`${first.id}-LOT`,'Illustrative identification; expiry and genealogy are not enforced'],'attr-quality':['Release status','Awaiting inspection','Customer release policy remains a requirement']};return table(['Product record','Example value','Planning effect'],[kinds[id]]);}
 if(id==='bom')return table(['Parent','Component','Quantity / order','Consuming operation'],def.materials.map((name,i)=>[first.product,name,i?first.quantity:1,def.route[0]]))+'<p>Illustrative structure; component receipt is executed only for the explicitly linked first order. Customer BOM versions and recursive rework require their own data.</p>';
 if(id.startsWith('master-')){const demand=100,opening=20,lot=inputs.lot||25,receipt=Math.ceil((demand-opening)/lot)*lot;return field('lot','Worked lot multiple',lot,1,1000)+table(['Bucket','Opening','Demand','Planned receipt','Closing'],[['D1–D7',opening,demand,receipt,opening+receipt-demand]])+'<p>Calculated example: round the 80-unit shortage up to the lot multiple. This bucket plan is not automatically released into the detailed schedule.</p>';}
 if(id==='architecture'||id==='execution'||id==='master-handoff')return table(['Object','Producer','Consumer','Timing','Contract still required'],[['Production order','ERP / master plan','APS','On release','Keys, quantity, revision and owner'],['Operation actual','MES / operator','APS + ERP','On completion','Event ID, actual quantity, time and failure handling']]);
 if(id==='areas'||id==='workcenters')return table(['Scenario asset','Route role','Capacity'],m.resources.map(r=>[r.name,r.group==='blend'?def.route[0]:def.route[1],'One operation at a time; daily calendar']))+'<p>Taxonomy describes required object types. These named assets belong to the reference case; replace them with actual site records for onboarding.</p>';
 if(id==='constraint')return '<p>Test candidates against delayed orders in the loading case. An occupied asset is a candidate, not proof that increasing it improves delivery.</p>';
 if(id==='transitions')return table(['Previous family','Next family','Clean duration','Resource release'],[['A','B','0.5 h','Previous processing end + cleaning'],['B','A','1.5 h','Previous processing end + cleaning'],['Last run','None','0 h','No terminal clean in this case']]);
 if(id.startsWith('dispatch-')){const r=schedule(m);return table(['Resource','First order','Starts','Reason'],m.resources.map(asset=>{const op=r.ops.find(o=>o.resource===asset.id);return [asset.name,op?.order||'None',op?time(op.start):'—','Earliest feasible start, then due date; manual order first'];}));}
 if(id==='variant')return '<p>This retained graph exercise is an illustrative branch, separate from your scheduling scenario. For an operational comparison, save a named scenario snapshot in the APS workspace; it contains inputs, revision and results.</p>';
 if(id==='migration')return '<p>Record the source, target, cutover timing and affected interfaces in the review evidence. Migration is an unresolved integration task, not a percentage penalty.</p>';
 if(id==='scope'||id==='welcome')return table(['Task','Output','Executable here'],[['Describe the operation','Resources, products, requirements','Captured decisions'],['Test a scenario','Resource sequence and delivery impact','APS with explicit assumptions'],['Prepare handoff','Decision evidence + adapter datasets','Synthetic data; customer acceptance pending']]);
 if(id==='industry'||id==='archetype'||id==='dialect')return table(['Case','Product','Operating route','Terminology'],[[def.name,def.product,def.route.join(' → '),'Canonical process names; ERP terms remain mappings']])+'<p>A reference case is a teaching and testing choice, not a claim to model every specialty in your project. Select the process that matches this question.</p>';
 return table(['Scenario field','Value'],rows);
}
export function attachDecisionContext({state,steps,render,save,representativeData,datasetParams}){
 const step=steps[state.i],root=document.querySelector('#stageBody'),body=root?.querySelector('.step-body');if(!body)return;
 const caseId=state.referenceCase||caseFor(state),def=cases[caseId],m=projectScenario(state,caseId),topic=topicOf(step.id),fingerprint=configurationKey(state);
 root.querySelector('.step-sub')?.classList.add('secondary-explanation');
 const block=document.createElement('section');block.className='decision-context';
 block.innerHTML=`<div class="case-heading"><div><strong>${esc(def.name)}</strong><small>Synthetic worked case · ${esc(def.product)}</small></div><label>Reference process<select id="referenceCase">${Object.entries(cases).map(([id,c])=>`<option value="${id}" ${id===caseId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label></div>${topic?(topic==='tank'&&!m.tank.enabled?'<p>No product-liquid inventory for this process. Choose Liquid medicine to inspect a vessel.</p>':experiment(topic,m)):detailFor(step.id,state,m,def)}`;
 if(topic){body.innerHTML='';root.querySelector('h2').textContent={capacity:'How much work fits in the shift?',bottleneck:'Which deliveries use the loaded assets?',tank:'Where does the liquid accumulate?',transition:'How much time does cleaning add?',workforce:'Which work waits for a specialist?'}[topic];root.querySelector('.step-sub')?.remove();}
 const contractScreen=['architecture','execution','master-handoff','migration'].includes(step.id);
 if(contractScreen){block.classList.add('contract-disclosure');block.querySelector('.case-heading')?.remove();body.append(block);}
 if(!contractScreen&&step.id!=='scope'&&!step.id.endsWith('-design')&&!['sop','mrp','qms','lims','plm'].includes(step.id))body.prepend(block);
 const charts=[...block.querySelectorAll('.case-pair>div')];if(charts.length===2){charts[0].hidden=true;block.querySelectorAll('[data-comparison]').forEach(b=>b.onclick=()=>{charts.forEach((el,i)=>el.hidden=i!==+b.dataset.comparison);block.querySelectorAll('[data-comparison]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});}
 if(block.querySelector('#referenceCase'))block.querySelector('#referenceCase').onchange=e=>{state.referenceCase=e.target.value;render();};
 block.querySelectorAll('[data-case-field]').forEach(input=>input.onchange=()=>{if(!input.reportValidity())return;state.scenarioInputs||={};state.scenarioInputs[input.dataset.caseField]=+input.value;if(input.dataset.caseField==='hours')state.calendar.hours=+input.value;render();});
 block.querySelectorAll('[data-contract]').forEach(input=>input.onchange=()=>{state.contracts||={};state.contracts[step.id]||={};state.contracts[step.id][input.dataset.contract]=input.value;render();});
 block.querySelectorAll('[data-asset-name]').forEach(input=>input.onchange=()=>{state.scenarioInputs||={};state.scenarioInputs.resourceNames||={};state.scenarioInputs.resourceNames[input.dataset.assetName]=input.value;render();});
 block.querySelectorAll('[data-route-hours]').forEach(input=>input.onchange=()=>{if(!input.reportValidity())return;state.scenarioInputs||={};state.scenarioInputs.routeHours||={};state.scenarioInputs.routeHours[input.dataset.routeHours]=+input.value;render();});
 const evidence=document.createElement('details');evidence.className='decision-evidence';const record=state.decisionEvidence?.[step.id];
 evidence.innerHTML=`<summary>${decisionState(state,step.id)} · decision owner and evidence</summary><p>Review records who checked the requirement and why. It does not certify scheduling feasibility. Any project change marks prior reviews for re-review.</p><label>Owner<input id="reviewOwner" value="${esc(record?.owner||'')}" required></label><label>Source / evidence<input id="reviewSource" value="${esc(record?.source||'')}" required placeholder="Document, record or meeting reference"></label><label>Rationale<textarea id="reviewRationale" required>${esc(record?.rationale||'')}</textarea></label><button id="saveReview" type="button">Record review</button>`;
 body.append(evidence);evidence.querySelector('#saveReview').onclick=()=>{const fields=['reviewOwner','reviewSource','reviewRationale'].map(id=>evidence.querySelector('#'+id));if(!fields.every(e=>e.reportValidity()&&e.value.trim()))return;state.decisionEvidence||={};state.decisionEvidence[step.id]={key:configurationKey(state),owner:fields[0].value,source:fields[1].value,rationale:fields[2].value,at:new Date().toISOString()};save();render();};
 if(step.id==='readiness'){
  const rows=steps.filter(s=>stepApplies(s.id,state)&&(s.gate||state.businessModules?.[s.id]?.enabled)).map(s=>({step:s,complete:s.gate?!!s.gate():true,review:decisionState(state,s.id),evidence:state.decisionEvidence?.[s.id]}));
  rows.sort((a,b)=>Number(a.complete)-Number(b.complete)||(a.review==='Reviewed')-(b.review==='Reviewed'));
  body.innerHTML=`<section class="decision-context"><div class="case-outcomes"><div><small>Missing decisions</small><strong>${rows.filter(r=>!r.complete).length}</strong></div><div><small>Need review</small><strong>${rows.filter(r=>r.review!=='Reviewed').length}</strong></div><div><small>Reviewed</small><strong>${rows.filter(r=>r.review==='Reviewed').length}</strong></div></div><p>Open an item to complete its decision or record the owner and evidence. Reviews apply to the current configuration.</p><div class="case-table-wrap"><table class="case-table"><thead><tr><th>Decision</th><th>Coverage</th><th>Review / owner</th><th>Next action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(typeof r.step.nav==='function'?r.step.nav():r.step.nav||r.step.id)}</td><td>${r.complete?'Captured':'Missing'}</td><td>${r.review}<br>${esc(r.evidence?.owner||'Unassigned')}</td><td><button data-review-step="${r.step.id}">${!r.complete?'Complete decision':r.review==='Reviewed'?'Inspect evidence':'Review decision'}</button></td></tr>`).join('')}</tbody></table></div><details><summary>Acceptance checks beyond decision review</summary><ul><li>Replace synthetic assets, orders, BOM and calendars with governed customer records.</li><li>Verify required constraints against the scenario projection; unsupported rules remain open.</li><li>Reconcile source-system keys, event contracts and adapter mappings.</li><li>Have planners validate delivery, shortage and disruption cases.</li></ul></details></section>`;
  body.querySelectorAll('[data-review-step]').forEach(button=>button.onclick=()=>{state.i=steps.findIndex(s=>s.id===button.dataset.reviewStep);state.max=Math.max(state.max,state.i);render();const detail=document.querySelector('.decision-evidence');if(detail){detail.open=true;detail.scrollIntoView({block:'nearest'});}});

 }
 if(step.id==='handoff'){
  if(state.scope!=='aps-ds'){body.innerHTML='';body.append(block,evidence);}
  const p=datasetParams(),g=representativeData();block.innerHTML=`<h3>Artifact manifest</h3>${table(['Artifact','Contents','Provenance'],[...(state.scope==='aps-ds'?[['Configured examples',`${g.departments.length} departments / ${g.resources.length} resources`,'One representative per selected taxonomy'],['Expanded adapter dataset',`${p.plants} plants; ${p.resInst} instances per resource type`,'Synthetic generator defaults; see adapter row estimates below']]:[]),['Decision record',`${Object.keys(state.decisionEvidence||{}).length} reviews`,'Owner, source, rationale and current / stale state'],['Working trials',state.scope==='aps-ds'?'APS and selected business trials':'Selected business trials','Export inputs and calculated results from the relevant trial'],['Module configuration',Object.keys(state.domainDesign||{}).length+' domain contracts','Requirements, owners, systems and acceptance cases in the implementation record']])}<button id="exportDecisionRecord">Export implementation record</button>`;
  block.querySelector('#exportDecisionRecord').onclick=()=>{const data={version:2,exportedAt:new Date().toISOString(),configuration:state,capabilities:selectedCapabilities(state).map(c=>({id:c.id,name:c.name})),domainContracts:state.domainDesign||{},evidence:state.decisionEvidence||{},scenarioProjection:m.projection,generatorParameters:p,validation:'Customer acceptance pending; generated data is synthetic'},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='implementation-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 }
}
