export const domainDesign={
 sop:{name:'S&OP',question:'How will the business agree and maintain the plan?',objects:'Product family · site · period · demand version · supply scenario',requirements:['Demand consensus and forecast ownership','Capacity and inventory tradeoffs','Financial reconciliation','Scenario approval and frozen periods','Exception thresholds and replanning cadence'],output:'Approved family / site / period volumes, assumptions and unresolved gaps'},
 mrp:{name:'MRP',question:'Which supply rules must material planning enforce?',objects:'Item · effective BOM · site · stock status · firm receipt · planned order',requirements:['Multilevel BOM explosion and effectivity','Lot sizing, safety stock and coverage policies','Supplier and production lead times','Pegging, shortage and expedite exceptions','Purchase / production order release controls'],output:'Time-phased planned receipts and releases with demand pegging and exceptions'},
 plm:{name:'PLM',question:'How does a product change become an executable definition?',objects:'Part · document · BOM revision · change request · effectivity',requirements:['Engineering and manufacturing BOM alignment','Document and specification revision control','Change review, approval and effectivity','Variant and configuration rules','Downstream publication and change impact'],output:'Approved product / BOM / specification revision with effectivity and change trace'},
 lims:{name:'LIMS',question:'How will a sample become a trusted laboratory result?',objects:'Sample · lot · test method · specification version · result · instrument',requirements:['Sampling plans and sample chain of custody','Test methods, limits and specification versions','Laboratory workload and instrument allocation','Result review and out-of-specification investigation','Result publication and retention controls'],output:'Reviewed results tied to sample, lot, method and specification version'},
 qms:{name:'QMS',question:'Who can contain, investigate and release a quality event?',objects:'Quality event · affected lot · nonconformance · action · disposition',requirements:['Inspection and nonconformance intake','Containment and affected-stock identification','Investigation and corrective-action ownership','Disposition authority and release evidence','Effectiveness review and closure criteria'],output:'Authorized disposition, affected stock and traceable corrective-action status'}
};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function registerDomainDesign({state,steps,render}){for(const [id,d] of Object.entries(domainDesign))steps.push({id:id+'-design',nav:d.name+' configuration',phase:d.name,title:d.question,sub:'Define the implementation contract. The worked trial tests a limited subset of these requirements.',hint:'Select required behavior and name the accountable owner and system of record.',gate:()=>{const c=state.domainDesign?.[id];return !!(c?.owner?.trim()&&c?.system?.trim()&&c?.requirements?.length);},body:()=>{const c=state.domainDesign?.[id]||{};return `<section class="domain-design"><h3>Required behavior</h3><div class="requirements-grid">${d.requirements.map((n,i)=>`<label><input type="checkbox" data-requirement="${i}" ${(c.requirements||[]).includes(i)?'checked':''}>${n}</label>`).join('')}</div><h3>Ownership and data contract</h3><p>${d.objects}</p><div class="contract-fields">${[['owner','Accountable process owner'],['system','System of record'],['source','Upstream source / input contract'],['consumer','Downstream consumer / output contract'],['cadence','Cadence, trigger or approval point'],['acceptance','Acceptance case and expected outcome']].map(([k,n])=>`<label>${n}<input data-design-field="${k}" value="${esc(c[k])}"></label>`).join('')}</div><p><strong>Expected handoff:</strong> ${d.output}</p><p class="note">Captured requirements are retained in the implementation record. A checked requirement is not proof that the trial enforces it.</p></section>`;},attach:root=>{const update=fn=>{state.domainDesign||={};state.domainDesign[id]||={};fn(state.domainDesign[id]);render();};root.querySelectorAll('[data-design-field]').forEach(e=>e.onchange=()=>update(c=>c[e.dataset.designField]=e.value));root.querySelectorAll('[data-requirement]').forEach(e=>e.onchange=()=>update(c=>{const set=new Set(c.requirements||[]);e.checked?set.add(+e.dataset.requirement):set.delete(+e.dataset.requirement);c.requirements=[...set];}));}});}
