export const transitions={A:{A:0,B:0.5,C:2},B:{A:1.5,B:0,C:1},C:{A:2,B:0.5,C:0}};
export function createModel(){
 return {version:1,name:'Northworks · Model 01',scope:['APS'],industry:'Process manufacturing',calendar:{hours:16},cleaning:{enabled:true,matrix:structuredClone(transitions)},tank:{capacity:250,batch:100},resources:[{id:'blend-1',name:'Blend 01',group:'blend'},{id:'blend-2',name:'Blend 02',group:'blend'},{id:'fill-1',name:'Fill 01',group:'fill'},{id:'fill-2',name:'Fill 02',group:'fill'}],orders:Array.from({length:12},(_,i)=>({id:`WO-${String(i+1).padStart(3,'0')}`,family:'ABC'[i%3],release:i<8?0:6,due:14+(i*13)%55,priority:1+i%5,operations:[{group:'blend',hours:2+i%3},{group:'fill',hours:1+(i*3)%4}]})),moves:{},rule:'due',budget:80};
}
export const topics=[
 {id:'scope',name:'Purpose & scope',tag:'Foundation',title:'Start with the decision you want to make.',text:'Use APS to turn orders into a feasible resource sequence. MOM and SCM remain visible as the wider implementation scope.',steps:['Pick the capabilities this model must support.','APS is executable now. Other capabilities are captured in the blueprint.','The scenario builder shows which configured inputs apply and which remain requirements.']},
 {id:'capacity',name:'Resources & calendars',tag:'Capacity',title:'A free machine is only free inside its calendar.',text:'Change daily working hours, then see orders move into the next available window.',steps:['Each row is a physical resource.','Shaded time is closed capacity. Work cannot start there.','Change the hours and compare the resulting schedule.']},
 {id:'cleaning',name:'Sequence & cleaning',tag:'Transitions',title:'The next product changes when this resource is free.',text:'Cleaning belongs to the end of the previous run. Material output stops at processing completion; resource occupancy includes the cleaning tail.',steps:['Solid bars show processing. Purple tails show cleaning.','Read the matrix from current family to next family.','Try cleaning-first dispatch, then let feedback search revisit the sequence.']},
 {id:'tank',name:'Tank & material flow',tag:'Secondary constraints',title:'Follow the liquid, not just the orders.',text:'Liquid enters during blending and leaves during filling. Capacity conflicts remain visible so you can explore the rough model.',steps:['A rising line means inflow; a falling line means consumption.','The dotted line is the tank capacity.','Tank overloads are diagnostic in this version; they do not block scheduling.']},
 {id:'orders',name:'Demand & priorities',tag:'Demand',title:'Put delivery promises next to production reality.',text:'Edit release times, due times and priorities. The next schedule reflects those changes immediately.',steps:['Release time is the earliest the order can begin.','Due time is the delivery promise. A red outline means late.','Compare less cleaning with the cost in late deliveries.']}
];
export const rules={due:'Earliest due date',short:'Shortest processing',priority:'Highest priority',clean:'Minimize cleaning',search:'Cleaning feedback search'};
export const time=t=>{const minutes=Math.round((t+6)*60);return `D${Math.floor(minutes/1440)+1} ${String(Math.floor(minutes/60)%24).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;};
